In [1]:
#Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv(r'Parkinsons Train Data_3.csv', header=0)

FileNotFoundError: [Errno 2] File Parkinsons Train Data_3.csv does not exist: 'Parkinsons Train Data_3.csv'

In [ ]:
data.head()

In [ ]:
data.shape

In [ ]:
data.index

In [ ]:
data.columns

In [ ]:
data.isnull().sum()

In [3]:
X = data.loc[:, data.columns != 'Class information'].values[:, 1:]
y = data.loc[:, 'Class information'].values

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,train_size = 0.98, stratify = data['Class information'])

In [5]:
X_train

array([[5.04900e+00, 4.16076e-04, 2.57600e+00, ..., 5.07040e+01,
        1.00000e+00, 1.35060e+01],
       [2.79800e+00, 2.37129e-04, 9.78000e-01, ..., 4.89210e+01,
        2.00000e+00, 1.96420e+01],
       [1.32600e+00, 6.82850e-05, 2.75000e-01, ..., 4.39390e+01,
        1.00000e+00, 3.26800e+01],
       ...,
       [4.01400e+00, 2.47715e-04, 1.70200e+00, ..., 3.15790e+01,
        1.00000e+00, 1.86320e+01],
       [2.76200e+00, 1.75934e-04, 1.39000e+00, ..., 4.68750e+01,
        1.00000e+00, 2.16140e+01],
       [2.48100e+00, 2.02288e-04, 9.86000e-01, ..., 3.27380e+01,
        6.00000e+00, 3.99710e+01]])

In [6]:
X_test

array([[1.26400000e+00, 1.00503000e-04, 7.91000000e-01, 6.76000000e-01,
        2.37300000e+00, 1.68720000e+01, 1.50400000e+00, 9.31600000e+00,
        9.77100000e+00, 1.38110000e+01, 2.79490000e+01, 9.18077000e-01,
        9.79020000e-02, 1.14930000e+01, 1.26074000e+02, 1.25781000e+02,
        1.99500000e+00, 1.19406000e+02, 1.34861000e+02, 5.57000000e+02,
        5.56000000e+02, 7.95316000e-03, 1.49089000e-04, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [1.39200000e+00, 5.98280000e-05, 4.37000000e-01, 4.80000000e-01,
        1.31000000e+00, 6.62700000e+00, 7.10000000e-01, 2.57100000e+00,
        3.52600000e+00, 6.32100000e+00, 7.71300000e+00, 9.27239000e-01,
        1.00403000e-01, 1.40570000e+01, 2.24039000e+02, 2.34976000e+02,
        3.47880000e+01, 1.44230000e+02, 3.19705000e+02, 2.36000000e+02,
        2.31000000e+02, 4.29669000e-03, 6.60781000e-04, 3.62500000e+01,
        2.00000000e+00, 2.76730000e+01],
       [1.32200000e+00, 9.67460000e-05, 6.80000000e-01

In [7]:
y_train

array([1, 1, 0, ..., 1, 0, 0], dtype=int64)

In [8]:
y_test

array([1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0],
      dtype=int64)

In [9]:
from sklearn.preprocessing import StandardScaler
standard_X = StandardScaler()

In [10]:
X_train = standard_X.fit_transform(X_train)
X_test = standard_X.fit_transform(X_test)

In [11]:
X_train

array([[ 1.35863489,  2.29164265,  1.37670354, ...,  1.09697963,
        -0.08097968,  0.08104638],
       [ 0.06689009,  0.61682533, -0.27830585, ...,  1.01186899,
         0.53702315,  0.48857176],
       [-0.77782263, -0.96343505, -1.00638571, ...,  0.77405561,
        -0.08097968,  1.35449678],
       ...,
       [ 0.76469625,  0.7159028 ,  0.47152318, ...,  0.18405697,
        -0.08097968,  0.42149213],
       [ 0.04623135,  0.04408343,  0.14839244, ...,  0.91420416,
        -0.08097968,  0.61954309],
       [-0.11502155,  0.29073822, -0.27002045, ...,  0.23938127,
         3.00903449,  1.83873203]])