In [1]:
#Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv(r'Parkinsons Train Data_3.csv', header=0)

In [3]:
data.head()

Subject Id  Jitter(local)  Jitter(local, absolute)  Jitter (rap)  \
0           1          1.488                 0.000090         0.900   
1           1          0.728                 0.000038         0.353   
2           1          1.220                 0.000074         0.732   
3           1          2.502                 0.000123         1.156   
4           1          3.509                 0.000167         1.715   

   Jitter (ppq5)  Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  \
0          0.794         2.699            8.334                0.779   
1          0.376         1.059            5.864                0.642   
2          0.670         2.196            8.719                0.875   
3          1.634         3.469           13.513                1.273   
4          1.539         5.145            9.112                1.040   

   Shimmer (apq3)  Shimmer (apq5)  ...  Minimum pitch  Maximum pitch  \
0           4.517           4.609  ...        142.229        187.576   
1           2.058           3.180  ...        159.515        234.505   
2           4.347           5.166  ...        146.445        211.442   
3           5.263           8.771  ...        182.713        220.230   
4           3.102           4.927  ...        182.821        225.162   

   Number of pulses  Number of periods  Mean period  \
0               160                159     0.006065   
1               170                169     0.005181   
2              1431               1427     0.006071   
3                94                 92     0.004910   
4               117                114     0.004757   

   Standard deviation of period  Fraction of locally unvoiced frames  \
0                      0.000416                                0.000   
1                      0.000403                                2.247   
2                      0.000474                               10.656   
3                      0.000320                                0.000   
4                      0.000380                               18.182   

   Number of voice breaks  Degree of voice breaks  Class information  
0                       0                   0.000                  1  
1                       0                   0.000                  1  
2                       1                   0.178                  1  
3                       0                   0.000                  1  
4                       1                  13.318                  1  

[5 rows x 28 columns]

In [4]:
data.shape

(1036, 28)

In [5]:
data.index

RangeIndex(start=0, stop=1036, step=1)

In [6]:
data.columns

Index(['Subject Id', 'Jitter(local)', 'Jitter(local, absolute)',
       'Jitter (rap)', 'Jitter (ppq5)', 'Jitter (ddp)', 'Shimmer (local)',
       'Shimmer (local, db)', 'Shimmer (apq3)', 'Shimmer (apq5)',
       'Shimmer (apq11)', 'Shimmer (dda)', 'AC', 'NDH', 'HTM', 'Median Pitch',
       'Mean Pitch', 'Standard deviation', 'Minimum pitch', 'Maximum pitch',
       'Number of pulses', 'Number of periods', 'Mean period',
       'Standard deviation of period', 'Fraction of locally unvoiced frames',
       'Number of voice breaks', 'Degree of voice breaks',
       'Class information'],
      dtype='object')

In [7]:
data.isnull().sum()

Subject Id                             0
Jitter(local)                          0
Jitter(local, absolute)                0
Jitter (rap)                           0
Jitter (ppq5)                          0
Jitter (ddp)                           0
Shimmer (local)                        0
Shimmer (local, db)                    0
Shimmer (apq3)                         0
Shimmer (apq5)                         0
Shimmer (apq11)                        0
Shimmer (dda)                          0
AC                                     0
NDH                                    0
HTM                                    0
Median Pitch                           0
Mean Pitch                             0
Standard deviation                     0
Minimum pitch                          0
Maximum pitch                          0
Number of pulses                       0
Number of periods                      0
Mean period                            0
Standard deviation of period           0
Fraction of loca

In [8]:
X = data.loc[:, data.columns != 'Class information'].values[:, 1:]
y = data.loc[:, 'Class information'].values

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,train_size = 0.98, stratify = data['Class information'])

In [10]:
X_train

array([[5.18900e+00, 3.96471e-04, 2.43300e+00, ..., 3.39620e+01,
        2.00000e+00, 3.24350e+01],
       [1.26300e+00, 7.59370e-05, 3.93000e-01, ..., 2.85710e+01,
        1.00000e+00, 1.12620e+01],
       [1.06900e+00, 6.32440e-05, 5.42000e-01, ..., 5.47620e+01,
        1.00000e+00, 2.35880e+01],
       ...,
       [4.33800e+00, 3.23565e-04, 2.05800e+00, ..., 2.17390e+01,
        0.00000e+00, 0.00000e+00],
       [1.28900e+00, 7.31470e-05, 6.23000e-01, ..., 3.50650e+01,
        1.00000e+00, 1.87490e+01],
       [2.77700e+00, 3.18193e-04, 1.36100e+00, ..., 3.80000e+01,
        0.00000e+00, 0.00000e+00]])

In [11]:
X_test

array([[1.90000000e-01, 6.49500000e-06, 8.80000000e-02, 8.10000000e-02,
        2.65000000e-01, 1.18500000e+00, 1.03000000e-01, 4.96000000e-01,
        7.08000000e-01, 1.28200000e+00, 1.48800000e+00, 9.97904000e-01,
        2.10600000e-03, 2.84180000e+01, 2.93066000e+02, 2.93096000e+02,
        5.47700000e+00, 2.73576000e+02, 3.05625000e+02, 3.10000000e+02,
        3.09000000e+02, 3.41224500e-03, 6.57080000e-05, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [4.38300000e+00, 2.98868000e-04, 1.51000000e+00, 1.42200000e+00,
        4.52900000e+00, 1.86150000e+01, 1.85400000e+00, 5.72500000e+00,
        1.14500000e+01, 9.46100000e+00, 1.71760000e+01, 7.56890000e-01,
        4.03009000e-01, 5.72800000e+00, 1.11772000e+02, 1.54742000e+02,
        1.22177000e+02, 9.45470000e+01, 4.94814000e+02, 5.90000000e+01,
        5.20000000e+01, 6.81826400e-03, 3.34358500e-03, 5.95510000e+01,
        3.00000000e+00, 1.61400000e+01],
       [1.40400000e+00, 1.34122000e-04, 7.00000000e-01

In [12]:
y_train

array([1, 0, 0, ..., 1, 0, 1], dtype=int64)

In [13]:
y_test

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1],
      dtype=int64)

In [14]:
from sklearn.preprocessing import StandardScaler
standard_X = StandardScaler()

In [15]:
X_train = standard_X.fit_transform(X_train)
X_test = standard_X.fit_transform(X_test)

In [16]:
X_train

array([[ 1.40748029,  2.11039595,  1.19647132, ...,  0.30153744,
         0.52369929,  1.30988242],
       [-0.80530211, -0.88885   , -0.87357379, ...,  0.04319343,
        -0.09081491, -0.08060337],
       [-0.9146449 , -1.00761877, -0.72237932, ...,  1.29830157,
        -0.09081491,  0.728877  ],
       ...,
       [ 0.92783744,  1.42821239,  0.81594832, ..., -0.28420525,
        -0.7053291 , -0.8202081 ],
       [-0.79064792, -0.91495611, -0.64018635, ...,  0.35439469,
        -0.09081491,  0.41108733],
       [ 0.04802254,  1.37794643,  0.10868291, ...,  0.49504386,
        -0.7053291 , -0.8202081 ]])

In [17]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [18]:
print("Accuracy for training set -> ", end = "")
Y_hat = [round(yhat) for yhat in model.predict(X)]
print(accuracy_score(y, Y_hat)) # Full set accuracy

Accuracy for training set -> 0.502895752895753


In [19]:
Y_hat = [round(yhat) for yhat in model.predict(X_test)]
print("Accuracy for test set -> ", end = "")
print(accuracy_score(y_test, Y_hat)) # Test set accuracy

Accuracy for test set -> 0.7619047619047619


In [20]:
test_data = pd.read_csv(r'Parkinsons Test Data_3.csv', header=0)
test_data=test_data.dropna()
print(test_data.shape)
print(list(test_data.columns))
test_data.head()

(189, 27)
['Subject Id', 'f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', 'f25']


Subject Id     f0        f1     f2     f3     f4     f5     f6     f7  \
0           1  0.135  0.000007  0.067  0.078  0.202  2.033  0.178  1.074   
1           1  0.143  0.000007  0.073  0.081  0.219  1.236  0.107  0.612   
2           1  0.162  0.000008  0.087  0.089  0.260  1.338  0.117  0.630   
3           1  0.140  0.000007  0.075  0.089  0.224  1.086  0.094  0.556   
4           1  0.150  0.000007  0.080  0.097  0.240  1.049  0.091  0.533   

      f8  ...    f16      f17      f18  f19  f20       f21       f22  f23  \
0  1.336  ...  0.859  184.502  187.880  183  182  0.005368  0.000025  0.0   
1  0.904  ...  0.755  198.665  202.214  194  193  0.004988  0.000020  0.0   
2  0.948  ...  1.860  197.220  206.060  198  197  0.004940  0.000046  0.0   
3  0.747  ...  0.931  202.324  206.182  200  199  0.004900  0.000023  0.0   
4  0.698  ...  0.880  205.407  209.927  204  203  0.004820  0.000022  0.0   

   f24  f25  
0    0  0.0  
1    0  0.0  
2    0  0.0  
3    0  0.0  
4    0  0.0  

[5 rows x 27 columns]

In [21]:
pred_cols = ['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', 'f25']

pred_X = test_data[pred_cols]

In [22]:
pred_X.head(20)

f0        f1     f2     f3     f4      f5     f6      f7      f8  \
0   0.135  0.000007  0.067  0.078  0.202   2.033  0.178   1.074   1.336   
1   0.143  0.000007  0.073  0.081  0.219   1.236  0.107   0.612   0.904   
2   0.162  0.000008  0.087  0.089  0.260   1.338  0.117   0.630   0.948   
3   0.140  0.000007  0.075  0.089  0.224   1.086  0.094   0.556   0.747   
4   0.150  0.000007  0.080  0.097  0.240   1.049  0.091   0.533   0.698   
5   0.208  0.000009  0.077  0.095  0.230   1.241  0.109   0.487   0.715   
6   1.137  0.000102  0.643  0.506  1.929   6.993  0.620   3.394   4.156   
7   0.606  0.000065  0.162  0.269  0.486   5.351  0.481   2.444   3.295   
8   0.765  0.000081  0.204  0.311  0.611   5.314  0.461   2.492   3.469   
9   0.374  0.000038  0.159  0.215  0.477   5.634  0.499   2.627   3.240   
10  0.543  0.000055  0.284  0.320  0.853   5.600  0.506   3.084   3.327   
11  0.336  0.000035  0.122  0.194  0.366   3.538  0.303   1.378   2.250   
12  5.238  0.000443  2.698  2.623  8.094  23.608  1.944  13.003   8.064   
13  3.700  0.000296  1.890  2.494  5.671  18.401  1.569  11.103  11.471   
14  1.259  0.000088  0.732  0.826  2.197   6.628  0.595   3.661   4.553   
15  1.443  0.000107  0.577  0.637  1.730   5.117  0.462   2.826   2.613   
16  1.335  0.000097  0.746  1.013  2.237   6.542  0.566   3.620   4.449   
17  1.228  0.000090  0.411  0.542  1.233   6.456  0.641   3.384   4.070   
18  1.397  0.000070  0.695  0.941  2.084   5.199  0.508   2.875   3.121   
19  1.525  0.000075  0.809  1.004  2.426  14.416  1.234   7.832   7.786   

           f9  ...     f16      f17      f18  f19  f20       f21       f22  \
0    1.576000  ...   0.859  184.502  187.880  183  182  0.005368  0.000025   
1    0.894000  ...   0.755  198.665  202.214  194  193  0.004988  0.000020   
2    1.017000  ...   1.860  197.220  206.060  198  197  0.004940  0.000046   
3    0.823000  ...   0.931  202.324  206.182  200  199  0.004900  0.000023   
4    0.777000  ...   0.880  205.407  209.927  204  203  0.004820  0.000022   
5    1.568000  ...   6.224  218.455  243.523  221  220  0.004416  0.000120   
6    6.189000  ...   4.301   97.914  119.037  110  109  0.009014  0.000370   
7    4.568000  ...   3.659   80.332   98.876   92   91  0.010768  0.000451   
8    5.992000  ...   3.686   88.629  104.526   93   92  0.010657  0.000411   
9    6.694000  ...   0.960   95.165   99.424   96   95  0.010280  0.000104   
10   4.679000  ...   1.143   97.088  102.247   98   97  0.010099  0.000121   
11   4.268000  ...   1.541   94.120  100.355   96   95  0.010310  0.000166   
12   4.210216  ...   5.319   98.268  133.337  108   99  0.008461  0.000738   
13  11.110000  ...   7.711   74.261  139.750  112  105  0.008003  0.000752   
14   5.647000  ...   1.267  139.308  146.279  142  141  0.006959  0.000120   
15   2.161000  ...  18.426   87.290  152.950  126  119  0.007449  0.001203   
16   6.136000  ...  12.560   82.093  146.001  122  114  0.007250  0.000519   
17   6.625000  ...  12.650   81.636  152.581  125  115  0.007320  0.000832   
18   3.909000  ...   3.954  191.158  207.135  195  194  0.005025  0.000131   
19   9.291000  ...   4.101  194.182  209.585  199  198  0.004937  0.000151   

       f23  f24    f25  
0    0.000    0  0.000  
1    0.000    0  0.000  
2    0.000    0  0.000  
3    0.000    0  0.000  
4    0.000    0  0.000  
5    0.000    0  0.000  
6    0.000    0  0.000  
7    0.000    0  0.000  
8    0.000    0  0.000  
9    0.000    0  0.000  
10   0.000    0  0.000  
11   0.000    0  0.000  
12   9.278    4  8.791  
13  13.402    3  8.552  
14   0.000    0  0.000  
15   1.031    2  3.478  
16   5.155    3  9.041  
17   2.062    3  5.866  
18   0.000    0  0.000  
19   0.000    0  0.000  

[20 rows x 26 columns]

In [23]:
predictions = model.predict(pred_X)
res = pd.DataFrame(predictions)
res.index = pred_X.index # its important for comparison
res.columns = ["Class Information"]
res.to_csv("Parkinsons Test Data predicted_check.csv")
#100% accuracy when testing the dataset.