# Hyperparameter tuning

## Importing the libraries

In [2]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn import model_selection
from xgboost import XGBClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.linear_model import LogisticRegression

## Import the dataset

In [2]:
#data = pd.read_csv(r'..\Datasets\Parkinsons Processed Training - Only Vowels - Sri Lankan.csv', header = 0)
data = pd.read_csv(r'..\Datasets\Sri Lankan Voice Recordings.csv', header = 0)
data.head()

Subject Id  Jitter(local)  Jitter(local, absolute)  Jitter (rap)  \
0           1        0.01488                 0.000090       0.00900   
1           1        0.00728                 0.000038       0.00353   
2           1        0.01220                 0.000074       0.00732   
3           2        0.00427                 0.000034       0.00243   
4           2        0.00844                 0.000069       0.00509   

   Jitter (ppq5)  Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  \
0        0.00794       0.02699          0.08334                0.779   
1        0.00376       0.01059          0.05864                0.642   
2        0.00670       0.02196          0.08719                0.875   
3        0.00249       0.00728          0.07428                0.694   
4        0.00489       0.01527          0.14053                1.239   

   Shimmer (apq3)  Shimmer (apq5)  ...  Maximum pitch  Number of pulses  \
0         0.04517         0.04609  ...        187.576               160   
1         0.02058         0.03180  ...        234.505               170   
2         0.04347         0.05166  ...        211.442              1431   
3         0.04205         0.04311  ...        129.205               345   
4         0.06131         0.07015  ...        126.788               585   

   Number of periods  Mean period  Standard deviation of period  \
0                159     0.006065                      0.000416   
1                169     0.005181                      0.000403   
2               1427     0.006071                      0.000474   
3                344     0.008073                      0.000143   
4                582     0.008174                      0.000123   

   Fraction of locally unvoiced frames  Number of voice breaks  \
0                              0.00000                       0   
1                              0.02247                       0   
2                              0.10656                       1   
3                              0.00000                       0   
4                              0.00209                       2   

   Degree of voice breaks  UPDRS  status  
0                 0.00000     23       1  
1                 0.00000     23       1  
2                 0.00178     23       1  
3                 0.00000      8       1  
4                 0.00768      8       1  

[5 rows x 29 columns]

In [3]:
data.shape

(120, 29)

In [4]:
X = data.iloc[:, 1:24].values
X

array([[1.488000e-02, 9.021300e-05, 9.000000e-03, ..., 1.590000e+02,
        6.064725e-03, 4.162760e-04],
       [7.280000e-03, 3.769800e-05, 3.530000e-03, ..., 1.690000e+02,
        5.181253e-03, 4.034940e-04],
       [1.220000e-02, 7.404100e-05, 7.320000e-03, ..., 1.427000e+03,
        6.070749e-03, 4.742890e-04],
       ...,
       [4.710000e-03, 3.383700e-05, 1.860000e-03, ..., 1.750000e+02,
        7.178780e-03, 1.298030e-04],
       [4.319000e-02, 3.171220e-04, 2.774000e-02, ..., 2.560000e+02,
        7.342534e-03, 3.119150e-04],
       [1.543000e-02, 1.033570e-04, 1.004000e-02, ..., 4.250000e+02,
        6.700038e-03, 1.082910e-04]])

In [5]:
y = data.iloc[:, -1].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [6]:
standard_X = StandardScaler()
X_scaled_standard = standard_X.fit_transform(X)
X_scaled_standard

array([[ 0.87868587,  0.77094821,  1.07622998, ..., -0.64799993,
        -0.18879174, -0.06122861],
       [-0.20384012, -0.39022832, -0.21557662, ..., -0.61325462,
        -0.75744717, -0.07935857],
       [ 0.49695302,  0.41336377,  0.67947768, ...,  3.75770466,
        -0.18491433,  0.02105691],
       ...,
       [-0.56990483, -0.47560017, -0.60996731, ..., -0.59240744,
         0.52828072, -0.46756133],
       [ 4.9110952 ,  5.78820816,  5.50190746, ..., -0.31097047,
         0.63368259, -0.20925404],
       [ 0.95702657,  1.06157954,  1.32183855, ...,  0.27622517,
         0.22013372, -0.49807391]])

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled_standard, y, random_state=12, test_size = 0.03, stratify = y)

In [8]:
X_train

array([[ 2.03243068e+00,  2.11502967e+00,  8.66045726e-01, ...,
        -1.06841811e+00,  1.29996886e-01, -4.88417066e-03],
       [-4.57379102e-01, -4.04534350e-01, -5.08417609e-01, ...,
         2.95335087e-02,  2.44406777e-01,  6.24127102e-01],
       [-2.03840119e-01, -3.90228319e-01, -2.15576623e-01, ...,
        -6.13254622e-01, -7.57447172e-01, -7.93585743e-02],
       ...,
       [ 4.32856090e-01,  5.25401886e-01,  5.18887461e-01, ...,
         9.19013300e-01,  2.42550462e-01,  8.90104518e+00],
       [-7.12342461e-01, -7.29394021e-01, -7.46941315e-01, ...,
        -4.88171526e-01, -2.09654682e-01,  1.08884147e-02],
       [ 3.13774670e+00,  2.29492746e+00,  3.24419792e+00, ...,
        -9.22487830e-01, -7.59941354e-01,  5.88509711e-01]])

In [9]:
X_test

array([[ 0.88580776,  0.18616985,  1.10456943,  1.02148997,  0.5017585 ,
         0.82422158,  0.88291856,  0.66926104,  0.79973733,  1.29691498,
         0.66936215, -0.38490124,  0.14346764, -1.1265146 ,  1.65847582,
         1.45528789,  0.14140209,  1.47389896,  0.56073736, -0.85434353,
        -0.84952269, -1.34419653, -0.25563566],
       [-0.55423669, -0.33879736, -0.71387862, -0.78764192, -0.44176821,
        -0.41268046, -0.42856324, -0.70789171, -0.47110632,  0.22056811,
        -0.70777823,  0.28504756, -0.18183412,  0.34972248, -1.04522078,
        -1.06531115, -0.15349823, -1.0778343 , -0.87100128, -0.6286788 ,
        -0.62715274,  1.2469842 ,  0.24034833],
       [-0.45880348, -0.47226136, -0.3596355 , -0.43983564, -0.25829333,
        -0.68993443, -0.68992616, -0.6520271 , -0.66922367, -0.88356788,
        -0.6521544 ,  0.375783  , -0.39791572, -0.02504765, -0.17302819,
        -0.15265831, -0.03269698,  0.02223609, -0.30941527, -0.65645292,
        -0.65147446, -0.1050

In [10]:
Y_train

array([1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1], dtype=int64)

In [11]:
Y_test

array([1, 0, 0, 1], dtype=int64)

## Performing Grid Search on Various Models

### Logistic Regression

In [12]:
log_param_grid = {'penalty' : ['l1', 'l2', 'elasticnet', 'none'], 'C' : range(0,100),
                  'solver' : ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'], 
}

In [13]:
model = LogisticRegression()
model_logreg = GridSearchCV(model, log_param_grid, cv=10, n_jobs = 4, verbose = 1)
model_logreg.fit(X_train, Y_train)

Fitting 10 folds for each of 2000 candidates, totalling 20000 fits


[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  68 tasks      | elapsed:    1.8s
[Parallel(n_jobs=4)]: Done 2380 tasks      | elapsed:    9.4s
[Parallel(n_jobs=4)]: Done 6380 tasks      | elapsed:   22.5s
[Parallel(n_jobs=4)]: Done 11980 tasks      | elapsed:   40.3s
[Parallel(n_jobs=4)]: Done 19180 tasks      | elapsed:  1.1min
[Parallel(n_jobs=4)]: Done 20000 out of 20000 | elapsed:  1.1min finished


GridSearchCV(cv=10, error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=4,
             param_grid={'C': range(0, 100),
                         'penalty': ['l1', 'l2', 'elasticnet', 'none'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=1)

In [14]:
model_logreg.best_params_

{'C': 15, 'penalty': 'l2', 'solver': 'newton-cg'}

In [15]:
model_logreg.best_score_

0.671969696969697

### Decision Trees

In [16]:
dec_trees_param_grid = {
    'criterion' : ['gini', 'entropy'], 'splitter' : ['best', 'random'],
    'max_depth' : range(1,16), 'min_samples_split' : range(5, 405, 5), 
    'min_samples_leaf' : range(5, 105, 5), 'max_leaf_nodes': range (2,21),
    'min_impurity_decrease': [0.00005, 0.00001, 0.0002, 0.0005, 0.001, 0.0015, 0.002, 0.005, 0.01,0.02,0.05,0.1,0.15,0.2,0.4]
}

In [45]:
dec_trees_param_grid = {
    'max_depth' : range(1,16), 'criterion' : ['gini', 'entropy'], 'splitter' : ['best', 'random'], 
    'min_samples_split' : range(0, 10), 'max_leaf_nodes': range(1,50, 5), 'min_impurity_decrease': np.arange(0.00001, 0.0001, -0.0001) } 

In [46]:
model = DecisionTreeClassifier(random_state=20)
model_dectree = GridSearchCV(model, dec_trees_param_grid, cv=10, n_jobs = 4, verbose = 1)
model_dectree.fit(X_train, Y_train)

Fitting 10 folds for each of 24000 candidates, totalling 240000 fits


[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done 312 tasks      | elapsed:    0.5s
[Parallel(n_jobs=4)]: Done 9720 tasks      | elapsed:    7.0s
[Parallel(n_jobs=4)]: Done 25720 tasks      | elapsed:   17.8s
[Parallel(n_jobs=4)]: Done 48120 tasks      | elapsed:   33.1s
[Parallel(n_jobs=4)]: Done 76920 tasks      | elapsed:   53.3s
[Parallel(n_jobs=4)]: Done 112120 tasks      | elapsed:  1.3min
[Parallel(n_jobs=4)]: Done 153720 tasks      | elapsed:  1.8min
[Parallel(n_jobs=4)]: Done 201720 tasks      | elapsed:  2.4min
[Parallel(n_jobs=4)]: Done 239993 out of 240000 | elapsed:  3.0min remaining:    0.0s
[Parallel(n_jobs=4)]: Done 240000 out of 240000 | elapsed:  3.0min finished


GridSearchCV(cv=10, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=20,
                                              splitter='best'),
             iid='deprecated', n_jobs=4,
             param_grid={'criterion': ['gini', 'entropy'],
                       

In [49]:
model_dectree.best_params_

{'criterion': 'gini',
 'max_depth': 8,
 'max_leaf_nodes': 21,
 'min_impurity_decrease': 1e-05,
 'min_samples_split': 6,
 'splitter': 'random'}

In [57]:
model_dectree.best_score_

0.6992424242424242

### Gradient Boosting

In [72]:
grad_boost_param_grid = {
    'loss' : ['deviance', 'exponential'], 'max_features' : ['auto', 'sqrt', 'log2', None], 
    'learning_rate' : np.arange(0.9, 0.7, -0.01), 'n_estimators' : range(10,120,10), 
    'max_depth' : range(2,6)
    }

In [73]:
model = GradientBoostingClassifier(random_state=20)
leave_one_out = model_selection.LeaveOneOut()
model_gradboost = GridSearchCV(model, grad_boost_param_grid, cv=leave_one_out, n_jobs = -1, verbose = 1)
model_gradboost.fit(X_scaled_standard, y)

Fitting 116 folds for each of 7392 candidates, totalling 857472 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:    0.3s
[Parallel(n_jobs=-1)]: Done 656 tasks      | elapsed:    7.3s
[Parallel(n_jobs=-1)]: Done 1656 tasks      | elapsed:   21.8s
[Parallel(n_jobs=-1)]: Done 3056 tasks      | elapsed:   36.2s
[Parallel(n_jobs=-1)]: Done 4856 tasks      | elapsed:   58.9s
[Parallel(n_jobs=-1)]: Done 7056 tasks      | elapsed:  1.4min
[Parallel(n_jobs=-1)]: Done 9656 tasks      | elapsed:  1.9min
[Parallel(n_jobs=-1)]: Done 12656 tasks      | elapsed:  2.6min
[Parallel(n_jobs=-1)]: Done 16056 tasks      | elapsed:  3.2min
[Parallel(n_jobs=-1)]: Done 19856 tasks      | elapsed:  4.0min
[Parallel(n_jobs=-1)]: Done 24467 tasks      | elapsed:  4.9min
[Parallel(n_jobs=-1)]: Done 28976 tasks      | elapsed:  5.9min
[Parallel(n_jobs=-1)]: Done 33976 tasks      | elapsed:  7.0min
[Parallel(n_jobs=-1)]: Done 39376 tasks      | elapsed:  8.2min
[Parallel(n_jobs=-1)]: Done 45922 tas

GridSearchCV(cv=LeaveOneOut(), error_score=nan,
             estimator=GradientBoostingClassifier(ccp_alpha=0.0,
                                                  criterion='friedman_mse',
                                                  init=None, learning_rate=0.1,
                                                  loss='deviance', max_depth=3,
                                                  max_features=None,
                                                  max_leaf_nodes=None,
                                                  min_impurity_decrease=0.0,
                                                  min_impurity_split=None,
                                                  min_samples_leaf=1,
                                                  min_samples_split=2,
                                                  min_weight_fraction_leaf=0.0,
                                                  n_estimators=100...
             param_grid={'learning_rate': array([0.9 , 0.89, 0.88, 0

In [74]:
model_gradboost.best_params_

{'learning_rate': 0.88,
 'loss': 'exponential',
 'max_depth': 2,
 'max_features': 'auto',
 'n_estimators': 40}

In [75]:
model_gradboost.best_score_

0.75

In [76]:
model_1 = GradientBoostingClassifier(random_state=20, learning_rate = 0.88, loss = 'exponential', max_depth = 2,
                                    max_features = 'auto', n_estimators = 40)
model_1.fit(X_train, Y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.88, loss='exponential', max_depth=2,
                           max_features='auto', max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=40,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=20, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [77]:
results = model_selection.cross_val_score(model_1, X_train, Y_train, cv=leave_one_out)

In [78]:
print("Accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100.0))

Accuracy: 75.000% (43.301%)


In [79]:
data_test = pd.read_csv(r'../Datasets/Sri Lankan Dataset - Finalised.csv', header = 0)
data_test.head()

Subject ID  Jitter(local)  Jitter(local, absolute)  Jitter (rap)  \
0          16       0.014680                 0.000086       0.00510   
1          16       0.001029                 0.000047       0.00407   
2          16       0.013350                 0.000056       0.00403   
3          16       0.021640                 0.000113       0.01130   
4          16       0.020900                 0.000095       0.00989   

   Jitter (ppq5)  Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  \
0        0.00615       0.01530          0.08510               0.0814   
1        0.00574       0.01220          0.04188               0.5570   
2        0.00663       0.01210          0.05257               0.7430   
3        0.01200       0.03389          0.06250               0.0781   
4        0.01107       0.02966          0.06128               0.8380   

   Shimmer (apq3)  Shimmer (apq5)  ...  Minimum pitch  Maximum pitch  \
0         0.03719         0.05185  ...         82.429        244.408   
1         0.01337         0.02081  ...        187.378        242.159   
2         0.01663         0.02859  ...        108.624        355.665   
3         0.01745         0.02950  ...        184.991        239.213   
4         0.02133         0.03216  ...        178.835        273.413   

   Number of pulses  Number of periods  Mean period  \
0                94                 93      0.00582   
1               113                112      0.00457   
2               122                120      0.00420   
3                69                 68      0.00524   
4                87                 86      0.00456   

   Standard deviation of period  Fraction of locally unvoiced frames  \
0                      0.001900                              0.00000   
1                      0.000297                              0.00641   
2                      0.000703                              0.02500   
3                      0.000254                              0.07759   
4                      0.000433                              0.01639   

   Number of voice breaks  Degree of voice breaks  status  
0                       0                     0.0       1  
1                       0                     0.0       1  
2                       0                     0.0       1  
3                       0                     0.0       1  
4                       0                     0.0       1  

[5 rows x 28 columns]

In [80]:
testing_X = data_test.iloc[:, 1:24].values
testing_X

array([[1.468e-02, 8.550e-05, 5.100e-03, ..., 9.300e+01, 5.820e-03,
        1.900e-03],
       [1.029e-03, 4.700e-05, 4.070e-03, ..., 1.120e+02, 4.570e-03,
        2.970e-04],
       [1.335e-02, 5.610e-05, 4.030e-03, ..., 1.200e+02, 4.200e-03,
        7.030e-04],
       ...,
       [6.290e-03, 6.700e-05, 3.600e-03, ..., 4.430e+02, 1.060e-02,
        1.460e-04],
       [3.880e-03, 4.110e-05, 2.000e-03, ..., 3.310e+02, 1.060e-02,
        1.600e-04],
       [8.550e-03, 7.950e-05, 4.150e-03, ..., 4.580e+02, 9.300e-03,
        2.520e-03]])

In [81]:
testing_X = standard_X.transform(testing_X)
testing_X

array([[ 0.85019835,  0.66673751,  0.15519785, ..., -0.87731893,
        -0.34631139,  2.04328249],
       [-1.09421775, -0.18454872, -0.0880491 , ..., -0.81130286,
        -1.15088617, -0.23040945],
       [ 0.6607563 ,  0.01666439, -0.09749558, ..., -0.78350661,
        -1.38904031,  0.34546013],
       ...,
       [-0.34485337,  0.25767789, -0.19904528, ...,  0.33876672,
         2.7303826 , -0.44458754],
       [-0.68812806, -0.31500557, -0.57690461, ..., -0.05038069,
         2.7303826 , -0.42472997],
       [-0.02294433,  0.53406953, -0.06915613, ...,  0.39088467,
         1.89362482,  2.92268923]])

In [82]:
y_predict_test = model_1.predict(testing_X)

In [83]:
y_predict_test

array([0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0], dtype=int64)

In [4]:
np.arange(0.9,0.7,-0.01)

array([0.9 , 0.89, 0.88, 0.87, 0.86, 0.85, 0.84, 0.83, 0.82, 0.81, 0.8 ,
       0.79, 0.78, 0.77, 0.76, 0.75, 0.74, 0.73, 0.72, 0.71, 0.7 ])