In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv(r'parkinsons_train.csv', header=0)

In [3]:
data.columns

Index(['MDVP:Fo(Hz)', 'MDVP:Fhi(Hz)', 'MDVP:Flo(Hz)', 'MDVP:Jitter(%)',
       'MDVP:Jitter(Abs)', 'MDVP:RAP', 'MDVP:PPQ', 'Jitter:DDP',
       'MDVP:Shimmer', 'MDVP:Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5',
       'MDVP:APQ', 'Shimmer:DDA', 'NHR', 'HNR', 'status', 'RPDE', 'DFA',
       'spread1', 'spread2', 'D2', 'PPE'],
      dtype='object')

In [4]:
y = data.loc[:, 'status'].values

In [5]:
cols_1 = ['MDVP:Fo(Hz)', 'MDVP:Fhi(Hz)',
       'MDVP:Jitter(Abs)', 'MDVP:RAP', 'Shimmer:APQ5',
       'MDVP:APQ', 'RPDE', 'DFA',
       'spread1', 'spread2', 'D2', 'PPE']

In [6]:
X = data[cols_1]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 12)

In [8]:
X_train

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Jitter(Abs)  MDVP:RAP  Shimmer:APQ5  \
26      242.852       255.034          0.000009   0.00117       0.00879   
79      148.790       158.359          0.000020   0.00152       0.00956   
46      228.969       239.541          0.000010   0.00136       0.01160   
21      186.163       197.724          0.000020   0.00165       0.00941   
19      180.198       201.249          0.000020   0.00153       0.00885   
..          ...           ...               ...       ...           ...   
3       167.930       193.221          0.000030   0.00220       0.02540   
2       153.880       172.860          0.000030   0.00232       0.02591   
6       104.400       206.002          0.000060   0.00316       0.02245   
27      245.510       262.090          0.000010   0.00127       0.00977   
75      117.004       144.466          0.000030   0.00176       0.01062   

    MDVP:APQ      RPDE       DFA   spread1   spread2        D2       PPE  
26   0.01014  0.431285  0.638928 -6.995820  0.102083  2.365800  0.102706  
79   0.01309  0.402591  0.762508 -6.311987  0.182459  2.251553  0.160306  
46   0.01234  0.305429  0.681811 -7.314237  0.006274  2.118596  0.091546  
21   0.01233  0.326480  0.765623 -6.647379  0.201095  2.374073  0.130554  
19   0.01190  0.403884  0.766209 -6.452058  0.212294  2.269398  0.141929  
..       ...       ...       ...       ...       ...       ...       ...  
3    0.04246  0.619060  0.679834 -4.330956  0.262384  2.916777  0.285695  
2    0.04525  0.629017  0.698951 -5.186960  0.237622  2.557536  0.259765  
6    0.03780  0.522746  0.737948 -5.571843  0.236853  2.846369  0.219514  
27   0.01149  0.467489  0.631653 -7.156076  0.127642  2.392122  0.097336  
75   0.01318  0.387482  0.756482 -6.012559  0.229298  1.872946  0.163118  

[72 rows x 12 columns]

In [9]:
from sklearn.preprocessing import StandardScaler
standard_X = StandardScaler()
standard_X.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
X_train = standard_X.transform(X_train)
X_test = standard_X.transform(X_test)
X_train

array([[ 1.75619315e+00,  5.22198918e-01, -8.41740784e-01,
        -5.97853781e-01, -6.58071126e-01, -7.95167075e-01,
        -2.41731677e-01, -1.49417977e+00, -8.33155160e-01,
        -1.31716901e+00,  3.83593170e-01, -8.22365578e-01],
       [-3.43927287e-01, -4.98289585e-01, -4.68262520e-01,
        -4.44853727e-01, -5.51163011e-01, -5.18609868e-01,
        -5.56145712e-01,  7.86082969e-01, -9.56436612e-02,
        -1.56384793e-01,  2.30483434e-02, -7.25832734e-02],
       [ 1.44622768e+00,  3.58656861e-01, -8.07788215e-01,
        -5.14796609e-01, -2.67925928e-01, -5.88921022e-01,
        -1.62079674e+00, -7.02914946e-01, -1.17656678e+00,
        -2.70083547e+00, -3.96542180e-01, -9.67635900e-01],
       [ 4.90498952e-01, -8.27578556e-02, -4.68262520e-01,
        -3.88025136e-01, -5.71989267e-01, -5.89858504e-01,
        -1.39013075e+00,  8.43560056e-01, -4.57362760e-01,
         1.12754933e-01,  4.09701403e-01, -4.59866661e-01],
       [ 3.57318514e-01, -4.55484222e-02, -4.6826252

In [11]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [12]:
model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [13]:
score = model.score(X_test, y_test)
print(score)

0.9166666666666666


In [14]:
y_pred = model.predict(X_test)

print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))
print("\n")

print("Classfications Results")
print(classification_report(y_test, y_pred))

print("Accuracy Score")
print(accuracy_score(y_test, y_pred))

Confusion Matrix
[[11  2]
 [ 0 11]]


Classfications Results
              precision    recall  f1-score   support

           0       1.00      0.85      0.92        13
           1       0.85      1.00      0.92        11

    accuracy                           0.92        24
   macro avg       0.92      0.92      0.92        24
weighted avg       0.93      0.92      0.92        24

Accuracy Score
0.9166666666666666


In [15]:
import pandas as pd
pred_data = pd.read_csv(r'parkinson_test.csv', header=0)
pred_data=pred_data.dropna()
print(pred_data.shape)
print(list(pred_data.columns))
pred_data.head()

(102, 22)
['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21']


f0       f1       f2       f3       f4       f5       f6       f7  \
0  119.992  157.302   74.997  0.00784  0.00007  0.00370  0.00554  0.01109   
1  122.400  148.650  113.819  0.00968  0.00008  0.00465  0.00696  0.01394   
2  116.682  131.111  111.555  0.01050  0.00009  0.00544  0.00781  0.01633   
3  116.676  137.871  111.366  0.00997  0.00009  0.00502  0.00698  0.01505   
4  116.014  141.781  110.655  0.01284  0.00011  0.00655  0.00908  0.01966   

        f8     f9  ...      f12      f13      f14     f15       f16       f17  \
0  0.04374  0.426  ...  0.02971  0.06545  0.02211  21.033  0.414783  0.815285   
1  0.06134  0.626  ...  0.04368  0.09403  0.01929  19.085  0.458359  0.819521   
2  0.05233  0.482  ...  0.03590  0.08270  0.01309  20.651  0.429895  0.825288   
3  0.05492  0.517  ...  0.03772  0.08771  0.01353  20.644  0.434969  0.819235   
4  0.06425  0.584  ...  0.04465  0.10470  0.01767  19.649  0.417356  0.823484   

        f18       f19       f20       f21  
0 -4.813031  0.266482  2.301442  0.284654  
1 -4.075192  0.335590  2.486855  0.368674  
2 -4.443179  0.311173  2.342259  0.332634  
3 -4.117501  0.334147  2.405554  0.368975  
4 -3.747787  0.234513  2.332180  0.410335  

[5 rows x 22 columns]

In [17]:
cols_pred = ['f0','f1', 'f4', 'f5', 'f11', 'f12', 'f16','f17', 'f18', 'f19', 'f20', 'f21']
pred_X = pred_data[cols_pred]
pred_X

f0       f1        f4       f5      f11      f12       f16  \
0    119.992  157.302  0.000070  0.00370  0.03130  0.02971  0.414783   
1    122.400  148.650  0.000080  0.00465  0.04518  0.04368  0.458359   
2    116.682  131.111  0.000090  0.00544  0.03858  0.03590  0.429895   
3    116.676  137.871  0.000090  0.00502  0.04005  0.03772  0.434969   
4    116.014  141.781  0.000110  0.00655  0.04825  0.04465  0.417356   
..       ...      ...       ...      ...      ...      ...       ...   
97   206.327  226.355  0.000020  0.00302  0.01284  0.01604  0.331508   
98   151.872  492.892  0.000060  0.00404  0.00832  0.01271  0.407701   
99   203.184  211.526  0.000009  0.00094  0.00610  0.00726  0.340068   
100  202.266  211.604  0.000009  0.00093  0.00606  0.00719  0.368535   
101  198.383  215.203  0.000010  0.00113  0.00825  0.00951  0.465946   

          f17       f18       f19       f20       f21  
0    0.815285 -4.813031  0.266482  2.301442  0.284654  
1    0.819521 -4.075192  0.335590  2.486855  0.368674  
2    0.825288 -4.443179  0.311173  2.342259  0.332634  
3    0.819235 -4.117501  0.334147  2.405554  0.368975  
4    0.823484 -3.747787  0.234513  2.332180  0.410335  
..        ...       ...       ...       ...       ...  
97   0.715121 -6.729713  0.181701  2.938114  0.115515  
98   0.662668 -4.673241  0.261549  2.702355  0.274407  
99   0.741899 -7.964984  0.163519  1.423287  0.044539  
100  0.742133 -7.695734  0.178540  1.544609  0.056141  
101  0.738703 -7.067931  0.175181  1.512275  0.096320  

[102 rows x 12 columns]

In [18]:
from sklearn.preprocessing import StandardScaler
standard_X = StandardScaler()
standard_X.fit(pred_X)
pred_X = standard_X.transform(pred_X)
pred_X

array([[-0.73223531, -0.36448009,  0.47109603, ...,  0.09625623,
        -0.45198879,  0.51525478],
       [-0.66644433, -0.46413935,  0.7392422 , ...,  0.94264486,
        -0.01210528,  1.49654152],
       [-0.82267058, -0.66616475,  1.00738838, ...,  0.64360175,
        -0.3551524 ,  1.075623  ],
       ...,
       [ 1.54072264,  0.26010655, -1.16459565, ..., -1.16476584,
        -2.53536974, -2.28909737],
       [ 1.51564119,  0.261005  , -1.16459565, ..., -0.98079867,
        -2.24753907, -2.15359524],
       [ 1.40955052,  0.30246058, -1.13778103, ..., -1.02193746,
        -2.32424994, -1.68433649]])

In [19]:
pred_y = model.predict(pred_X)
res = pd.DataFrame(pred_y)
res.columns = ["status"]
res.to_csv("XG Boost limited features - predictions.csv")