In [1]:
#importing the libraries needed for ML
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
plt.rc("font", size=14)
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv(r'..\Datasets\Parkinsons Train Data.csv', header = 0)
data.head()

Jitter(local)  Jitter(local, absolute)  Jitter (rap)  Jitter (ppq5)  \
0          1.488                 0.000090         0.900          0.794   
1          0.728                 0.000038         0.353          0.376   
2          1.220                 0.000074         0.732          0.670   
3          2.502                 0.000123         1.156          1.634   
4          3.509                 0.000167         1.715          1.539   

   Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  Shimmer (apq3)  \
0         2.699            8.334                0.779           4.517   
1         1.059            5.864                0.642           2.058   
2         2.196            8.719                0.875           4.347   
3         3.469           13.513                1.273           5.263   
4         5.145            9.112                1.040           3.102   

   Shimmer (apq5)  Shimmer (apq11)  ...  Minimum pitch  Maximum pitch  \
0           4.609            6.802  ...        142.229        187.576   
1           3.180            7.194  ...        159.515        234.505   
2           5.166            7.548  ...        146.445        211.442   
3           8.771           16.779  ...        182.713        220.230   
4           4.927           12.823  ...        182.821        225.162   

   Number of pulses  Number of periods  Mean period  \
0               160                159     0.006065   
1               170                169     0.005181   
2              1431               1427     0.006071   
3                94                 92     0.004910   
4               117                114     0.004757   

   Standard deviation of period  Fraction of locally unvoiced frames  \
0                      0.000416                                0.000   
1                      0.000403                                2.247   
2                      0.000474                               10.656   
3                      0.000320                                0.000   
4                      0.000380                               18.182   

   Number of voice breaks  Degree of voice breaks  status  
0                       0                   0.000       1  
1                       0                   0.000       1  
2                       1                   0.178       1  
3                       0                   0.000       1  
4                       1                  13.318       1  

[5 rows x 27 columns]

In [3]:
#setting the dependent variable
y = data.iloc[:, -1].values
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [4]:
X = data.iloc[:, :-1].values
X

array([[1.48800e+00, 9.02130e-05, 9.00000e-01, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [7.28000e-01, 3.76980e-05, 3.53000e-01, ..., 2.24700e+00,
        0.00000e+00, 0.00000e+00],
       [1.22000e+00, 7.40410e-05, 7.32000e-01, ..., 1.06560e+01,
        1.00000e+00, 1.78000e-01],
       ...,
       [2.91200e+00, 2.26205e-04, 1.14100e+00, ..., 2.00000e+01,
        1.00000e+00, 4.57400e+00],
       [3.78800e+00, 2.74883e-04, 1.78600e+00, ..., 1.66670e+01,
        3.00000e+00, 1.95750e+01],
       [1.80900e+00, 1.48510e-04, 6.80000e-01, ..., 1.81820e+01,
        1.00000e+00, 3.38700e+00]])

In [5]:
from sklearn.preprocessing import StandardScaler
standard_X = StandardScaler()
standard_scaled_X = standard_X.fit_transform(X)
standard_scaled_X

array([[-0.67709317, -0.75525109, -0.35596897, ..., -1.32200138,
        -0.70349085, -0.81748742],
       [-1.10769097, -1.24846346, -0.91419898, ..., -1.21483914,
        -0.70349085, -0.81748742],
       [-0.82893555, -0.9071359 , -0.52741804, ..., -0.81380343,
        -0.0848011 , -0.80575498],
       ...,
       [ 0.12971113,  0.52196373, -0.11002119, ..., -0.3681764 ,
        -0.0848011 , -0.51600327],
       [ 0.62603176,  0.97913962,  0.54822078, ..., -0.52713133,
         1.15257839,  0.47275138],
       [-0.49522226, -0.20773512, -0.58048561, ..., -0.45487909,
        -0.0848011 , -0.5942415 ]])

In [6]:
def standardScale(X):
    X = standard_X.transform(X)
    return X

In [7]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
minmax_scaled_X = min_max_scaler.fit_transform(X)
minmax_scaled_X

array([[0.09149866, 0.108709  , 0.1053558 , ..., 0.        , 0.        ,
        0.        ],
       [0.03792471, 0.04051754, 0.03658537, ..., 0.02548833, 0.        ,
        0.        ],
       [0.0726068 , 0.08770943, 0.08423435, ..., 0.12087389, 0.08333333,
        0.00257534],
       ...,
       [0.19187932, 0.28529654, 0.13565502, ..., 0.2268654 , 0.08333333,
        0.06617764],
       [0.25363034, 0.34850561, 0.21674629, ..., 0.18905828, 0.25      ,
        0.28321542],
       [0.1141266 , 0.18440848, 0.07769676, ..., 0.20624334, 0.08333333,
        0.04900386]])

In [8]:
def minmaxScale(X):
    X = min_max_scaler.transform(X)
    return X

In [9]:
data.columns

Index(['Jitter(local)', 'Jitter(local, absolute)', 'Jitter (rap)',
       'Jitter (ppq5)', 'Jitter (ddp)', 'Shimmer (local)',
       'Shimmer (local, db)', 'Shimmer (apq3)', 'Shimmer (apq5)',
       'Shimmer (apq11)', 'Shimmer (dda)', 'AC', 'NDH', 'HTM', 'Median Pitch',
       'Mean Pitch', 'Standard deviation', 'Minimum pitch', 'Maximum pitch',
       'Number of pulses', 'Number of periods', 'Mean period',
       'Standard deviation of period', 'Fraction of locally unvoiced frames',
       'Number of voice breaks', 'Degree of voice breaks', 'status'],
      dtype='object')

In [10]:
fixed_cols = ['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods',
              'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks']
jitter_cols = ['Jitter(local)', 'Jitter(local, absolute)', 'Jitter (rap)','Jitter (ppq5)', 'Jitter (ddp)']
shimmer_cols = ['Shimmer (local)', 'Shimmer (local, db)', 'Shimmer (apq3)', 'Shimmer (apq5)', 'Shimmer (apq11)',
                'Shimmer (dda)']
pitch_cols = ['Median Pitch', 'Mean Pitch']

In [11]:
def getSVM(X, y):
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=12, test_size= 0.2)
    from sklearn.svm import SVC
    from sklearn import metrics
    svc = SVC()
    svc.fit(X_train, y_train)
    print("Accuracy on training set: {:.4f}".format(svc.score(X_train, y_train)))
    print("Accuracy on test set: {:.4f}".format(svc.score(X_test, y_test)))
    
    #MinMaxScalar
    print("\nUsing MinMaxScaler")
    from sklearn.preprocessing import MinMaxScaler

    scaler = MinMaxScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.fit_transform(X_test)

    svc = SVC()
    svc.fit(X_train_scaled, y_train)

    print("Accuracy on training set: {:.4f}".format(svc.score(X_train_scaled, y_train)))
    print("Accuracy on test set: {:.4f}".format(svc.score(X_test_scaled, y_test)))
    
    #Scale
    print("\nUsing scaled values")
    svc = SVC(C=1000)
    svc.fit(X_train_scaled, y_train)

    print("Accuracy on training set: {:.4f}".format(
        svc.score(X_train_scaled, y_train)))
    print("Accuracy on test set: {:.4f}".format(svc.score(X_test_scaled, y_test)))

In [12]:
for jitter in jitter_cols:
    for shimmer in shimmer_cols:
        for pitch in pitch_cols:
            
            fixed_cols.append(jitter)
            fixed_cols.append(shimmer)
            fixed_cols.append(pitch)
            print(fixed_cols)
            print("\n")
            print("Added columns to the dataset are:", jitter, shimmer, pitch)
            print("\n")
            X = data[fixed_cols].values
            print("---------Standard Scaled---------")
            print("\n")
            standard_X = StandardScaler()
            standard_scaled_X = standard_X.fit_transform(X)
            standard_scaled_X
            getSVM(standard_scaled_X, y)
            print("\n")
            print("---------MinMax Scaled---------")
            print("\n")
            min_max_scaler = preprocessing.MinMaxScaler()
            minmax_scaled_X = min_max_scaler.fit_transform(X)
            minmax_scaled_X
            getSVM(minmax_scaled_X, y)
            fixed_cols.remove(jitter)
            fixed_cols.remove(shimmer)
            fixed_cols.remove(pitch)
            print("\n")

['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter(local)', 'Shimmer (local)', 'Median Pitch']


Added columns to the dataset are: Jitter(local) Shimmer (local) Median Pitch


---------Standard Scaled---------


Accuracy on training set: 0.7222
Accuracy on test set: 0.7019

Using MinMaxScaler
Accuracy on training set: 0.6932
Accuracy on test set: 0.6683

Using scaled values
Accuracy on training set: 0.9215
Accuracy on test set: 0.7019


---------MinMax Scaled---------


Accuracy on training set: 0.6908
Accuracy on test set: 0.6635

Using MinMaxScaler
Accuracy on training set: 0.6932
Accuracy on test set: 0.6683

Using scaled values
Accuracy on training set: 0.9215
Accuracy on test set: 0.7019


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoi

Accuracy on training set: 0.6957
Accuracy on test set: 0.6683

Using scaled values
Accuracy on training set: 0.9215
Accuracy on test set: 0.6298


---------MinMax Scaled---------


Accuracy on training set: 0.6920
Accuracy on test set: 0.6875

Using MinMaxScaler
Accuracy on training set: 0.6957
Accuracy on test set: 0.6683

Using scaled values
Accuracy on training set: 0.9215
Accuracy on test set: 0.6298


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter(local)', 'Shimmer (dda)', 'Median Pitch']


Added columns to the dataset are: Jitter(local) Shimmer (dda) Median Pitch


---------Standard Scaled---------


Accuracy on training set: 0.7114
Accuracy on test set: 0.6827

Using MinMaxScaler
Accuracy on training set: 0.6848
Accuracy on test set: 0.6538

Using scaled values
Accuracy on training set: 0.9143
Accuracy on test set: 0.6

Accuracy on training set: 0.9118
Accuracy on test set: 0.7019


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter(local, absolute)', 'Shimmer (apq5)', 'Mean Pitch']


Added columns to the dataset are: Jitter(local, absolute) Shimmer (apq5) Mean Pitch


---------Standard Scaled---------


Accuracy on training set: 0.7234
Accuracy on test set: 0.6875

Using MinMaxScaler
Accuracy on training set: 0.6775
Accuracy on test set: 0.6635

Using scaled values
Accuracy on training set: 0.9179
Accuracy on test set: 0.6683


---------MinMax Scaled---------


Accuracy on training set: 0.6787
Accuracy on test set: 0.6538

Using MinMaxScaler
Accuracy on training set: 0.6775
Accuracy on test set: 0.6635

Using scaled values
Accuracy on training set: 0.9179
Accuracy on test set: 0.6683


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Num

Accuracy on test set: 0.6779

Using MinMaxScaler
Accuracy on training set: 0.6824
Accuracy on test set: 0.6490

Using scaled values
Accuracy on training set: 0.9118
Accuracy on test set: 0.6923


---------MinMax Scaled---------


Accuracy on training set: 0.6812
Accuracy on test set: 0.6635

Using MinMaxScaler
Accuracy on training set: 0.6824
Accuracy on test set: 0.6490

Using scaled values
Accuracy on training set: 0.9118
Accuracy on test set: 0.6923


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter (rap)', 'Shimmer (apq3)', 'Mean Pitch']


Added columns to the dataset are: Jitter (rap) Shimmer (apq3) Mean Pitch


---------Standard Scaled---------


Accuracy on training set: 0.7114
Accuracy on test set: 0.6779

Using MinMaxScaler
Accuracy on training set: 0.6800
Accuracy on test set: 0.6490

Using scaled values
Accuracy on t

Accuracy on training set: 0.7307
Accuracy on test set: 0.6971

Using MinMaxScaler
Accuracy on training set: 0.6896
Accuracy on test set: 0.6635

Using scaled values
Accuracy on training set: 0.9022
Accuracy on test set: 0.6635


---------MinMax Scaled---------


Accuracy on training set: 0.6932
Accuracy on test set: 0.6683

Using MinMaxScaler
Accuracy on training set: 0.6896
Accuracy on test set: 0.6635

Using scaled values
Accuracy on training set: 0.9022
Accuracy on test set: 0.6635


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter (ppq5)', 'Shimmer (local, db)', 'Mean Pitch']


Added columns to the dataset are: Jitter (ppq5) Shimmer (local, db) Mean Pitch


---------Standard Scaled---------


Accuracy on training set: 0.7271
Accuracy on test set: 0.7067

Using MinMaxScaler
Accuracy on training set: 0.6860
Accuracy on test s

Accuracy on training set: 0.7307
Accuracy on test set: 0.6827

Using MinMaxScaler
Accuracy on training set: 0.6908
Accuracy on test set: 0.6683

Using scaled values
Accuracy on training set: 0.9191
Accuracy on test set: 0.6731


---------MinMax Scaled---------


Accuracy on training set: 0.6896
Accuracy on test set: 0.6731

Using MinMaxScaler
Accuracy on training set: 0.6908
Accuracy on test set: 0.6683

Using scaled values
Accuracy on training set: 0.9191
Accuracy on test set: 0.6731


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter (ddp)', 'Shimmer (local)', 'Mean Pitch']


Added columns to the dataset are: Jitter (ddp) Shimmer (local) Mean Pitch


---------Standard Scaled---------


Accuracy on training set: 0.7283
Accuracy on test set: 0.6923

Using MinMaxScaler
Accuracy on training set: 0.6920
Accuracy on test set: 0.6779

Accuracy on test set: 0.6779

Using MinMaxScaler
Accuracy on training set: 0.6812
Accuracy on test set: 0.6490

Using scaled values
Accuracy on training set: 0.9118
Accuracy on test set: 0.6923


---------MinMax Scaled---------


Accuracy on training set: 0.6812
Accuracy on test set: 0.6635

Using MinMaxScaler
Accuracy on training set: 0.6812
Accuracy on test set: 0.6490

Using scaled values
Accuracy on training set: 0.9118
Accuracy on test set: 0.6923


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter (ddp)', 'Shimmer (dda)', 'Mean Pitch']


Added columns to the dataset are: Jitter (ddp) Shimmer (dda) Mean Pitch


---------Standard Scaled---------


Accuracy on training set: 0.7114
Accuracy on test set: 0.6779

Using MinMaxScaler
Accuracy on training set: 0.6787
Accuracy on test set: 0.6490

Using scaled values
Accuracy on tra

In [13]:
fixed_cols

['AC',
 'NDH',
 'HTM',
 'Minimum pitch',
 'Maximum pitch',
 'Number of pulses',
 'Number of periods',
 'Mean period',
 'Fraction of locally unvoiced frames',
 'Number of voice breaks',
 'Degree of voice breaks']

In [14]:
getSVM(minmax_scaled_X, y)

Accuracy on training set: 0.6812
Accuracy on test set: 0.6683

Using MinMaxScaler
Accuracy on training set: 0.6787
Accuracy on test set: 0.6490

Using scaled values
Accuracy on training set: 0.9094
Accuracy on test set: 0.6635


In [15]:
getSVM(standard_scaled_X, y)

Accuracy on training set: 0.7114
Accuracy on test set: 0.6779

Using MinMaxScaler
Accuracy on training set: 0.6787
Accuracy on test set: 0.6490

Using scaled values
Accuracy on training set: 0.9094
Accuracy on test set: 0.6635
