In [73]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score

In [74]:
data = pd.read_csv(r'..\Datasets\Train Data with UPDRS_Only Vowels.csv', header = 0)
data.head()

Subject ID  Jitter(local)  Jitter(local, absolute)  Jitter (rap)  \
0           1          1.488                 0.000090         0.900   
1           1          0.728                 0.000038         0.353   
2           1          1.220                 0.000074         0.732   
3           2          0.427                 0.000034         0.243   
4           2          0.844                 0.000069         0.509   

   Jitter (ppq5)  Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  \
0          0.794         2.699            8.334                0.779   
1          0.376         1.059            5.864                0.642   
2          0.670         2.196            8.719                0.875   
3          0.249         0.728            7.428                0.694   
4          0.489         1.527           14.053                1.239   

   Shimmer (apq3)  Shimmer (apq5)  ...  Minimum pitch  Maximum pitch  \
0           4.517           4.609  ...        142.229        187.576   
1           2.058           3.180  ...        159.515        234.505   
2           4.347           5.166  ...        146.445        211.442   
3           4.205           4.311  ...        118.461        129.205   
4           6.131           7.015  ...        118.020        126.788   

   Number of pulses  Number of periods  Mean period  \
0               160                159     0.006065   
1               170                169     0.005181   
2              1431               1427     0.006071   
3               345                344     0.008073   
4               585                582     0.008174   

   Standard deviation of period  Fraction of locally unvoiced frames  \
0                      0.000416                                0.000   
1                      0.000403                                2.247   
2                      0.000474                               10.656   
3                      0.000143                                0.000   
4                      0.000123                                0.209   

   Number of voice breaks  Degree of voice breaks  status  
0                       0                   0.000       1  
1                       0                   0.000       1  
2                       1                   0.178       1  
3                       0                   0.000       1  
4                       2                   0.768       1  

[5 rows x 28 columns]

In [75]:
X = data.iloc[:, 1:-1].values
X

array([[1.48800e+00, 9.02130e-05, 9.00000e-01, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [7.28000e-01, 3.76980e-05, 3.53000e-01, ..., 2.24700e+00,
        0.00000e+00, 0.00000e+00],
       [1.22000e+00, 7.40410e-05, 7.32000e-01, ..., 1.06560e+01,
        1.00000e+00, 1.78000e-01],
       ...,
       [4.71000e-01, 3.38370e-05, 1.86000e-01, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [4.31900e+00, 3.17122e-04, 2.77400e+00, ..., 2.91300e+00,
        1.00000e+00, 7.03800e+00],
       [1.54300e+00, 1.03357e-04, 1.00400e+00, ..., 3.51000e-01,
        0.00000e+00, 0.00000e+00]])

In [76]:
y = data.iloc[:, -1].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [77]:
standard_X = StandardScaler()
standard_scaled_X = standard_X.fit_transform(X)
standard_scaled_X

array([[ 0.95200109,  0.84480825,  1.09023877, ..., -0.49321641,
        -0.35850613, -0.26520441],
       [-0.14968145, -0.32962626, -0.2011674 , ..., -0.09898599,
        -0.35850613, -0.26520441],
       [ 0.56351303,  0.48314102,  0.69360945, ...,  1.37635161,
         0.69078011, -0.22328107],
       ...,
       [-0.5222241 , -0.41597286, -0.59543583, ..., -0.49321641,
        -0.35850613, -0.26520441],
       [ 5.05576855,  5.91935384,  5.51454435, ...,  0.01786201,
         0.69078011,  1.39241639],
       [ 1.03172811,  1.13875793,  1.3357712 , ..., -0.43163435,
        -0.35850613, -0.26520441]])

In [119]:
# Train
svclassifier = SVC(probability = True)
svclassifier.fit(standard_scaled_X, y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [120]:
y_pred_standard = svclassifier.predict(standard_scaled_X)

In [121]:
cm = confusion_matrix(y, y_pred_standard) # Calulate Confusion matrix for test set.
cm

array([[32, 28],
       [ 5, 55]], dtype=int64)

In [122]:
print("Classfications Results")
print(classification_report(y, y_pred_standard))

Classfications Results
              precision    recall  f1-score   support

           0       0.86      0.53      0.66        60
           1       0.66      0.92      0.77        60

    accuracy                           0.73       120
   macro avg       0.76      0.72      0.71       120
weighted avg       0.76      0.72      0.71       120



In [123]:
pred_data = pd.read_csv(r'..\Datasets\Sri Lankan Dataset Optimized.csv', header = 0)
pred_data.head(11)

Subject ID  Jitter(local)  Jitter(local, absolute)  Jitter (rap)  \
0            7        0.00454                 0.000024       0.00268   
1            7        0.00237                 0.000014       0.00109   
2            7        0.00499                 0.000023       0.00222   
3            7        0.00348                 0.000019       0.00148   
4            7        0.00252                 0.000012       0.00117   
5            7        0.00338                 0.000016       0.00166   
6            8        0.00442                 0.000035       0.00220   
7            8        0.00241                 0.000016       0.00111   
8            8        0.00467                 0.000029       0.00255   
9            8        0.00444                 0.000032       0.00235   
10        1011        0.00598                 0.000044       0.00342   

    Jitter (ppq5)  Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  \
0         0.00251       0.00805          0.02804                0.247   
1         0.00134       0.00328          0.03529                0.487   
2         0.00225       0.00667          0.02655                0.254   
3         0.00190       0.00443          0.06244                0.589   
4         0.00129       0.00350          0.01137                0.104   
5         0.00185       0.00497          0.01657                0.157   
6         0.00227       0.00661          0.05617                0.506   
7         0.00153       0.00334          0.09308                0.787   
8         0.00223       0.00765          0.01153                0.117   
9         0.00241       0.00705          0.03187                0.298   
10        0.00364       0.01025          0.06036                0.537   

    Shimmer (apq3)  Shimmer (apq5)  ...  Standard deviation  Minimum pitch  \
0          0.01478         0.01741  ...              12.352         83.120   
1          0.01389         0.01970  ...              45.593         97.088   
2          0.01120         0.01371  ...              31.613         72.648   
3          0.02163         0.03215  ...              38.166         89.138   
4          0.00420         0.00566  ...               3.912        190.920   
5          0.00717         0.00955  ...              28.632        104.453   
6          0.03075         0.03717  ...               3.784         85.431   
7          0.03388         0.06473  ...               1.371        149.630   
8          0.00542         0.00617  ...              40.425         78.148   
9          0.01817         0.01943  ...               3.866        121.200   
10         0.02922         0.04016  ...               2.031        132.570   

    Maximum pitch  Number of pulses  Number of periods  Mean period  \
0         199.481              1970               1968     0.005304   
1         219.312              1825               1821     0.005852   
2         397.254              1401               1387     0.004551   
3         381.381              1722               1717     0.005475   
4         243.271              1323               1322     0.004903   
5         254.245              1430               1425     0.004672   
6         149.840               695                693     0.007823   
7         158.486               987                986     0.006465   
8         347.153              1051               1050     0.006301   
9         175.151               923                921     0.007316   
10        144.448               448                445     0.007286   

    Standard deviation of period  Fraction of locally unvoiced frames  \
0                       0.000460                               10.309   
1                       0.001895                               13.750   
2                       0.000712                               16.966   
3                       0.001401                                9.386   
4                       0.000097                               13.715   
5                       0.000813  

In [124]:
pred_X = pred_data.iloc[:, 1:].values
pred_X

array([[4.540000e-03, 2.405700e-05, 2.680000e-03, 2.510000e-03,
        8.050000e-03, 2.804000e-02, 2.470000e-01, 1.478000e-02,
        1.741000e-02, 2.258000e-02, 4.434000e-02, 9.910670e-01,
        1.052600e-02, 2.341200e+01, 1.898940e+02, 1.883840e+02,
        1.235200e+01, 8.312000e+01, 1.994810e+02, 1.970000e+03,
        1.968000e+03, 5.304283e-03, 4.601280e-04, 1.030900e+01,
        0.000000e+00, 0.000000e+00],
       [2.370000e-03, 1.384800e-05, 1.090000e-03, 1.340000e-03,
        3.280000e-03, 3.529000e-02, 4.870000e-01, 1.389000e-02,
        1.970000e-02, 3.545000e-02, 4.167000e-02, 9.884280e-01,
        1.211700e-02, 2.473500e+01, 1.976060e+02, 1.712280e+02,
        4.559300e+01, 9.708800e+01, 2.193120e+02, 1.825000e+03,
        1.821000e+03, 5.851503e-03, 1.894846e-03, 1.375000e+01,
        2.000000e+00, 1.429000e+00],
       [4.990000e-03, 2.271800e-05, 2.220000e-03, 2.250000e-03,
        6.670000e-03, 2.655000e-02, 2.540000e-01, 1.120000e-02,
        1.371000e-02, 2.490000

In [125]:
pred_X_scaled = standard_X.transform(pred_X)
pred_X_scaled

array([[-1.19839625e+00, -6.34690742e-01, -1.02823396e+00,
        -1.16355456e+00, -1.02809415e+00, -1.50926502e+00,
        -1.08491258e+00, -1.37165630e+00, -1.28599434e+00,
        -1.65625367e+00, -1.37166358e+00,  6.73333906e-01,
        -5.83110230e-01,  1.18575660e+00,  4.23383739e-01,
         3.52998906e-01,  5.87230685e-02, -1.41323896e+00,
        -9.74576571e-02,  5.15771193e+00,  5.16102537e+00,
        -5.97126083e-01,  2.50999888e-01,  1.31547134e+00,
        -3.58506131e-01, -2.65204412e-01],
       [-1.20154185e+00, -8.63002690e-01, -1.03198777e+00,
        -1.16672458e+00, -1.03184765e+00, -1.50783150e+00,
        -5.26857884e-01, -1.37197393e+00, -1.28537265e+00,
        -1.65281398e+00, -1.37198120e+00,  6.37674761e-01,
        -5.70067302e-01,  1.42427298e+00,  5.85853142e-01,
        -4.94389896e-03,  1.86331636e+00, -1.11843116e+00,
         1.28483833e-01,  4.69178670e+00,  4.68851978e+00,
        -2.68643157e-01,  4.10124799e+00,  1.91918601e+00,
         1.74

In [126]:
y_predictions = svclassifier.predict(pred_X_scaled)
y_predictions

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [129]:
y_pred_standard_proba = svclassifier.predict_log_proba(pred_X_scaled)
print(y_pred_standard_proba)

[[-0.67203482 -0.71471491]
 [-0.5916524  -0.80611896]
 [-0.55062712 -0.85940984]
 [-0.59292806 -0.80454043]
 [-0.59509284 -0.80187193]
 [-0.57402207 -0.82840674]
 [-0.49089943 -0.94694488]
 [-0.66965702 -0.71720243]
 [-0.53769555 -0.87729292]
 [-0.50627764 -0.92315172]
 [-0.47435914 -0.97361196]]


In [86]:
min_max_scaler = preprocessing.MinMaxScaler()
minmax_scaled_X = min_max_scaler.fit_transform(X)
minmax_scaled_X

array([[0.31436183, 0.26951295, 0.30899705, ..., 0.        , 0.        ,
        0.        ],
       [0.13029789, 0.10045167, 0.10730088, ..., 0.0642    , 0.        ,
        0.        ],
       [0.24945507, 0.21745051, 0.24705015, ..., 0.30445714, 0.16666667,
        0.00674702],
       ...,
       [0.06805522, 0.08802197, 0.04572271, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 1.        , ..., 0.08322857, 0.16666667,
        0.2667728 ],
       [0.32768225, 0.31182737, 0.34734513, ..., 0.01002857, 0.        ,
        0.        ]])

In [112]:
# Train
svclassifier2 = SVC(probability=True )
svclassifier2.fit(minmax_scaled_X, y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [113]:
pred_y_minmax = svclassifier2.predict(minmax_scaled_X)

In [114]:
print("Classfications Results")
print(classification_report(y, pred_y_minmax))

Classfications Results
              precision    recall  f1-score   support

           0       0.78      0.52      0.62        60
           1       0.64      0.85      0.73        60

    accuracy                           0.68       120
   macro avg       0.71      0.68      0.67       120
weighted avg       0.71      0.68      0.67       120



In [115]:
pred_X_scaled_minmax = min_max_scaler.transform(pred_X)
pred_X_scaled_minmax

array([[-4.49164447e-02,  5.65372617e-02, -2.18731563e-02,
        -3.95017614e-02, -2.17463439e-02, -5.13337474e-02,
         7.75862069e-02, -3.89588731e-02, -3.27355897e-02,
        -7.62100174e-02, -3.89588731e-02,  9.81907721e-01,
         1.30042627e-02,  8.08829145e-01,  3.86372931e-01,
         3.81362910e-01,  8.15574227e-02,  3.43003326e-02,
         2.33556056e-01,  1.33613445e+00,  1.33426378e+00,
         3.13545688e-01,  1.79903946e-01,  2.94542857e-01,
         0.00000000e+00,  0.00000000e+00],
       [-4.54419956e-02,  2.36714774e-02, -2.24594395e-02,
        -4.00905888e-02, -2.23325550e-02, -5.10120685e-02,
         2.06896552e-01, -3.90309262e-02, -3.26270383e-02,
        -7.54122242e-02, -3.90309262e-02,  9.74924318e-01,
         1.54614814e-02,  8.59352326e-01,  4.17911241e-01,
         3.10730695e-01,  3.12757345e-01,  9.35590891e-02,
         2.84401906e-01,  1.23459384e+00,  1.23168179e+00,
         3.86515078e-01,  8.17560925e-01,  3.92857143e-01,
         3.33

In [116]:
y_predictions_minmax = svclassifier2.predict(pred_X_scaled_minmax)
y_predictions_minmax

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [117]:
y_predict_proba = svclassifier2.predict_proba(pred_X_scaled_minmax)

In [118]:
print(y_predict_proba)

[[0.5        0.5       ]
 [0.55788282 0.44211718]
 [0.6222385  0.3777615 ]
 [0.56166765 0.43833235]
 [0.56802511 0.43197489]
 [0.58249789 0.41750211]
 [0.66105531 0.33894469]
 [0.50866723 0.49133277]
 [0.66182417 0.33817583]
 [0.62030899 0.37969101]
 [0.63956258 0.36043742]]
