In [1]:
#importing the libraries needed for ML
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
plt.rc("font", size=14)
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

In [20]:
data = pd.read_csv(r'..\Datasets\Train Data with UPDRS_Only Vowels.csv', header = 0)
data.head()

Subject ID  Jitter(local)  Jitter(local, absolute)  Jitter (rap)  \
0           1          1.488                 0.000090         0.900   
1           1          0.728                 0.000038         0.353   
2           1          1.220                 0.000074         0.732   
3           2          0.427                 0.000034         0.243   
4           2          0.844                 0.000069         0.509   

   Jitter (ppq5)  Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  \
0          0.794         2.699            8.334                0.779   
1          0.376         1.059            5.864                0.642   
2          0.670         2.196            8.719                0.875   
3          0.249         0.728            7.428                0.694   
4          0.489         1.527           14.053                1.239   

   Shimmer (apq3)  Shimmer (apq5)  ...  Minimum pitch  Maximum pitch  \
0           4.517           4.609  ...        142.229        187.576   
1           2.058           3.180  ...        159.515        234.505   
2           4.347           5.166  ...        146.445        211.442   
3           4.205           4.311  ...        118.461        129.205   
4           6.131           7.015  ...        118.020        126.788   

   Number of pulses  Number of periods  Mean period  \
0               160                159     0.006065   
1               170                169     0.005181   
2              1431               1427     0.006071   
3               345                344     0.008073   
4               585                582     0.008174   

   Standard deviation of period  Fraction of locally unvoiced frames  \
0                      0.000416                                0.000   
1                      0.000403                                2.247   
2                      0.000474                               10.656   
3                      0.000143                                0.000   
4                      0.000123                                0.209   

   Number of voice breaks  Degree of voice breaks  status  
0                       0                   0.000       1  
1                       0                   0.000       1  
2                       1                   0.178       1  
3                       0                   0.000       1  
4                       2                   0.768       1  

[5 rows x 28 columns]

In [3]:
data.shape

(120, 28)

In [4]:
data.columns

Index(['Subject ID', 'Jitter(local)', 'Jitter(local, absolute)',
       'Jitter (rap)', 'Jitter (ppq5)', 'Jitter (ddp)', 'Shimmer (local)',
       'Shimmer (local, db)', 'Shimmer (apq3)', 'Shimmer (apq5)',
       'Shimmer (apq11)', 'Shimmer (dda)', 'AC', 'NDH', 'HTM', 'Median Pitch',
       'Mean Pitch', 'Standard deviation', 'Minimum pitch', 'Maximum pitch',
       'Number of pulses', 'Number of periods', 'Mean period',
       'Standard deviation of period', 'Fraction of locally unvoiced frames',
       'Number of voice breaks', 'Degree of voice breaks', 'status'],
      dtype='object')

In [21]:
#setting the dependent variable
y = data.iloc[:, -1].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [22]:
X = data.iloc[:, 1:-1].values
X

array([[1.48800e+00, 9.02130e-05, 9.00000e-01, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [7.28000e-01, 3.76980e-05, 3.53000e-01, ..., 2.24700e+00,
        0.00000e+00, 0.00000e+00],
       [1.22000e+00, 7.40410e-05, 7.32000e-01, ..., 1.06560e+01,
        1.00000e+00, 1.78000e-01],
       ...,
       [4.71000e-01, 3.38370e-05, 1.86000e-01, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [4.31900e+00, 3.17122e-04, 2.77400e+00, ..., 2.91300e+00,
        1.00000e+00, 7.03800e+00],
       [1.54300e+00, 1.03357e-04, 1.00400e+00, ..., 3.51000e-01,
        0.00000e+00, 0.00000e+00]])

In [50]:
X[10].size

26

In [7]:
from sklearn.preprocessing import StandardScaler
standard_X = StandardScaler()
standard_scaled_X = standard_X.fit_transform(X)
standard_scaled_X

array([[ 0.95200109,  0.84480825,  1.09023877, ..., -0.49321641,
        -0.35850613, -0.26520441],
       [-0.14968145, -0.32962626, -0.2011674 , ..., -0.09898599,
        -0.35850613, -0.26520441],
       [ 0.56351303,  0.48314102,  0.69360945, ...,  1.37635161,
         0.69078011, -0.22328107],
       ...,
       [-0.5222241 , -0.41597286, -0.59543583, ..., -0.49321641,
        -0.35850613, -0.26520441],
       [ 5.05576855,  5.91935384,  5.51454435, ...,  0.01786201,
         0.69078011,  1.39241639],
       [ 1.03172811,  1.13875793,  1.3357712 , ..., -0.43163435,
        -0.35850613, -0.26520441]])

In [48]:
def standardScale(X):
    X = standard_X.transform(X)
    return X

In [23]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
minmax_scaled_X = min_max_scaler.fit_transform(X)
minmax_scaled_X

array([[0.31436183, 0.26951295, 0.30899705, ..., 0.        , 0.        ,
        0.        ],
       [0.13029789, 0.10045167, 0.10730088, ..., 0.0642    , 0.        ,
        0.        ],
       [0.24945507, 0.21745051, 0.24705015, ..., 0.30445714, 0.16666667,
        0.00674702],
       ...,
       [0.06805522, 0.08802197, 0.04572271, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 1.        , ..., 0.08322857, 0.16666667,
        0.2667728 ],
       [0.32768225, 0.31182737, 0.34734513, ..., 0.01002857, 0.        ,
        0.        ]])

In [10]:
def minmaxScale(X):
    X = min_max_scaler.transform(X)
    return X

In [34]:
data.columns

Index(['Subject ID', 'Jitter(local)', 'Jitter(local, absolute)',
       'Jitter (rap)', 'Jitter (ppq5)', 'Jitter (ddp)', 'Shimmer (local)',
       'Shimmer (local, db)', 'Shimmer (apq3)', 'Shimmer (apq5)',
       'Shimmer (apq11)', 'Shimmer (dda)', 'Mean Pitch', 'Minimum pitch',
       'Maximum pitch', 'status'],
      dtype='object')

In [52]:
fixed_cols = ['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods',
              'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks']
jitter_cols = ['Jitter(local)', 'Jitter(local, absolute)', 'Jitter (rap)','Jitter (ppq5)', 'Jitter (ddp)']
shimmer_cols = ['Shimmer (local)', 'Shimmer (local, db)', 'Shimmer (apq3)', 'Shimmer (apq5)', 'Shimmer (apq11)',
                'Shimmer (dda)']
pitch_cols = ['Median Pitch', 'Mean Pitch']

In [53]:
def getXGBoost(X, y):
    
    from sklearn.model_selection import train_test_split
    from sklearn.metrics import accuracy_score
    X_train, X_test, Y_train, Y_test = train_test_split(X, y, random_state=12, test_size = 0.2)
    # Train
    from xgboost import XGBClassifier
    model = XGBClassifier()
    model.fit(X_train, Y_train)

    # Evaluate
    print("Accuracy for training set -> ", end = "")
    Y_hat = [round(yhat) for yhat in model.predict(X)]
    print(accuracy_score(y, Y_hat)) # Full set accuracy
    Y_hat = [round(yhat) for yhat in model.predict(X_test)]
    print("Accuracy for test set -> ", end = "")
    print(accuracy_score(Y_test, Y_hat)) # Test set accuracy

    #Validations
    y_pred = model.predict(X_test)

    #Confusion Matrix
    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(Y_test, y_pred) # Calulate Confusion matrix for test set.
    print(cm)

    from sklearn.model_selection import cross_val_score
    accuracies = cross_val_score(estimator = model, X = X_train, y = Y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [54]:
for jitter in jitter_cols:
    for shimmer in shimmer_cols:
        for pitch in pitch_cols:
            
            fixed_cols.append(jitter)
            fixed_cols.append(shimmer)
            fixed_cols.append(pitch)
            print(fixed_cols)
            print("\n")
            print("Added columns to the dataset are:", jitter, shimmer, pitch)
            print("\n")
            X = data[fixed_cols].values
            print("---------Standard Scaled---------")
            print("\n")
            standard_X = StandardScaler()
            standard_scaled_X = standard_X.fit_transform(X)
            standard_scaled_X
            getXGBoost(standard_scaled_X, y)
            print("\n")
            print("---------MinMax Scaled---------")
            print("\n")
            min_max_scaler = preprocessing.MinMaxScaler()
            minmax_scaled_X = min_max_scaler.fit_transform(X)
            minmax_scaled_X
            getXGBoost(minmax_scaled_X, y)
            fixed_cols.remove(jitter)
            fixed_cols.remove(shimmer)
            fixed_cols.remove(pitch)
            print("\n")

['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter(local)', 'Shimmer (local)', 'Median Pitch']


Added columns to the dataset are: Jitter(local) Shimmer (local) Median Pitch


---------Standard Scaled---------


Accuracy for training set -> 0.925
Accuracy for test set -> 0.625
[[ 4  5]
 [ 4 11]]
Accuracy: 67.56 %
Standard Deviation: 10.37 %


---------MinMax Scaled---------


Accuracy for training set -> 0.925
Accuracy for test set -> 0.625
[[ 4  5]
 [ 4 11]]
Accuracy: 67.56 %
Standard Deviation: 10.37 %


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter(local)', 'Shimmer (local)', 'Mean Pitch']


Added columns to the dataset are: Jitter(local) Shimmer (local) Mean Pitch


Accuracy: 67.67 %
Standard Deviation: 12.40 %


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter(local, absolute)', 'Shimmer (local)', 'Median Pitch']


Added columns to the dataset are: Jitter(local, absolute) Shimmer (local) Median Pitch


---------Standard Scaled---------


Accuracy for training set -> 0.9333333333333333
Accuracy for test set -> 0.6666666666666666
[[ 6  3]
 [ 5 10]]
Accuracy: 69.67 %
Standard Deviation: 11.79 %


---------MinMax Scaled---------


Accuracy for training set -> 0.9333333333333333
Accuracy for test set -> 0.6666666666666666
[[ 6  3]
 [ 5 10]]
Accuracy: 69.67 %
Standard Deviation: 11.79 %


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter

Accuracy: 67.78 %
Standard Deviation: 11.36 %


---------MinMax Scaled---------


Accuracy for training set -> 0.9333333333333333
Accuracy for test set -> 0.6666666666666666
[[ 6  3]
 [ 5 10]]
Accuracy: 67.78 %
Standard Deviation: 11.36 %


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter (rap)', 'Shimmer (local)', 'Median Pitch']


Added columns to the dataset are: Jitter (rap) Shimmer (local) Median Pitch


---------Standard Scaled---------


Accuracy for training set -> 0.925
Accuracy for test set -> 0.625
[[ 4  5]
 [ 4 11]]
Accuracy: 70.89 %
Standard Deviation: 7.32 %


---------MinMax Scaled---------


Accuracy for training set -> 0.925
Accuracy for test set -> 0.625
[[ 4  5]
 [ 4 11]]
Accuracy: 70.89 %
Standard Deviation: 7.32 %


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of period

Accuracy: 66.78 %
Standard Deviation: 10.44 %


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter (ppq5)', 'Shimmer (local)', 'Median Pitch']


Added columns to the dataset are: Jitter (ppq5) Shimmer (local) Median Pitch


---------Standard Scaled---------


Accuracy for training set -> 0.925
Accuracy for test set -> 0.625
[[ 4  5]
 [ 4 11]]
Accuracy: 70.78 %
Standard Deviation: 9.94 %


---------MinMax Scaled---------


Accuracy for training set -> 0.925
Accuracy for test set -> 0.625
[[ 4  5]
 [ 4 11]]
Accuracy: 70.78 %
Standard Deviation: 9.94 %


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter (ppq5)', 'Shimmer (local)', 'Mean Pitch']


Added columns to the dataset 

Accuracy: 70.89 %
Standard Deviation: 7.32 %


---------MinMax Scaled---------


Accuracy for training set -> 0.925
Accuracy for test set -> 0.625
[[ 4  5]
 [ 4 11]]
Accuracy: 70.89 %
Standard Deviation: 7.32 %


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter (ddp)', 'Shimmer (local)', 'Mean Pitch']


Added columns to the dataset are: Jitter (ddp) Shimmer (local) Mean Pitch


---------Standard Scaled---------


Accuracy for training set -> 0.925
Accuracy for test set -> 0.625
[[ 4  5]
 [ 4 11]]
Accuracy: 68.67 %
Standard Deviation: 9.35 %


---------MinMax Scaled---------


Accuracy for training set -> 0.925
Accuracy for test set -> 0.625
[[ 4  5]
 [ 4 11]]
Accuracy: 68.67 %
Standard Deviation: 9.35 %


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of 

In [ ]:
fixed_cols

In [ ]:
getXGBoost(minmax_scaled_X, y)

In [ ]:
getXGBoost(standard_scaled_X, y)

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
#X_train, X_test, Y_train, Y_test = train_test_split(X, y, random_state=12, test_size = 0.05)

In [24]:
# Train
from sklearn.svm import SVC
svclassifier = SVC()
svclassifier.fit(minmax_scaled_X, y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [25]:
standard_scaled_X

array([[ 0.95200109,  0.84480825,  1.09023877, ..., -0.49321641,
        -0.35850613, -0.26520441],
       [-0.14968145, -0.32962626, -0.2011674 , ..., -0.09898599,
        -0.35850613, -0.26520441],
       [ 0.56351303,  0.48314102,  0.69360945, ...,  1.37635161,
         0.69078011, -0.22328107],
       ...,
       [-0.5222241 , -0.41597286, -0.59543583, ..., -0.49321641,
        -0.35850613, -0.26520441],
       [ 5.05576855,  5.91935384,  5.51454435, ...,  0.01786201,
         0.69078011,  1.39241639],
       [ 1.03172811,  1.13875793,  1.3357712 , ..., -0.43163435,
        -0.35850613, -0.26520441]])

In [39]:
X_test

array([[1.00500e+00, 6.46780e-05, 3.98000e-01, 3.60000e-01, 1.19400e+00,
        3.63800e+00, 4.59000e-01, 1.59800e+00, 2.18100e+00, 3.46100e+00,
        4.79500e+00, 1.55269e+02, 1.37347e+02, 1.67642e+02],
       [1.09100e+00, 5.92370e-05, 6.55000e-01, 5.53000e-01, 1.96500e+00,
        1.60460e+01, 1.36300e+00, 8.31400e+00, 1.32030e+01, 1.10540e+01,
        2.49420e+01, 1.84172e+02, 1.70612e+02, 2.55594e+02],
       [2.96000e-01, 2.03310e-05, 9.80000e-02, 1.33000e-01, 2.93000e-01,
        3.02200e+00, 2.88000e-01, 1.16400e+00, 1.52900e+00, 2.99600e+00,
        3.49100e+00, 1.45490e+02, 1.37541e+02, 1.55351e+02],
       [8.26000e-01, 5.72710e-05, 2.44000e-01, 3.14000e-01, 7.33000e-01,
        6.75600e+00, 7.10000e-01, 2.40100e+00, 3.13000e+00, 8.06900e+00,
        7.20300e+00, 1.46796e+02, 1.25803e+02, 4.70707e+02],
       [1.14500e+00, 5.22520e-05, 5.53000e-01, 4.48000e-01, 1.65900e+00,
        7.28300e+00, 6.44000e-01, 3.55900e+00, 4.47600e+00, 6.72100e+00,
        1.06760e+01, 2.198

In [69]:
y_pred = svclassifier.predict(X_test)

In [70]:
y_pred

array([1, 1, 1, 0, 1, 1], dtype=int64)

In [27]:
y_train_pred = svclassifier.predict(minmax_scaled_X)

In [28]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y, y_train_pred) # Calulate Confusion matrix for test set.
cm

array([[31, 29],
       [ 9, 51]], dtype=int64)

In [29]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("Classfications Results")
print(classification_report(y, y_train_pred))

Classfications Results
              precision    recall  f1-score   support

           0       0.78      0.52      0.62        60
           1       0.64      0.85      0.73        60

    accuracy                           0.68       120
   macro avg       0.71      0.68      0.67       120
weighted avg       0.71      0.68      0.67       120



In [14]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred) # Calulate Confusion matrix for test set.
print(cm)

NameError: name 'Y_test' is not defined

In [73]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = svclassifier, X = X_train, y = Y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 54.32 %
Standard Deviation: 11.30 %


In [30]:
pred_data = pd.read_csv(r'..\Datasets\Sri Lankan Dataset Optimized.csv', header = 0)
pred_data.head()

Subject ID  Jitter(local)  Jitter(local, absolute)  Jitter (rap)  \
0           7        0.00454                 0.000024       0.00268   
1           7        0.00237                 0.000014       0.00109   
2           7        0.00499                 0.000023       0.00222   
3           7        0.00348                 0.000019       0.00148   
4           7        0.00252                 0.000012       0.00117   

   Jitter (ppq5)  Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  \
0        0.00251       0.00805          0.02804                0.247   
1        0.00134       0.00328          0.03529                0.487   
2        0.00225       0.00667          0.02655                0.254   
3        0.00190       0.00443          0.06244                0.589   
4        0.00129       0.00350          0.01137                0.104   

   Shimmer (apq3)  Shimmer (apq5)  ...  Standard deviation  Minimum pitch  \
0         0.01478         0.01741  ...              12.352         83.120   
1         0.01389         0.01970  ...              45.593         97.088   
2         0.01120         0.01371  ...              31.613         72.648   
3         0.02163         0.03215  ...              38.166         89.138   
4         0.00420         0.00566  ...               3.912        190.920   

   Maximum pitch  Number of pulses  Number of periods  Mean period  \
0        199.481              1970               1968     0.005304   
1        219.312              1825               1821     0.005852   
2        397.254              1401               1387     0.004551   
3        381.381              1722               1717     0.005475   
4        243.271              1323               1322     0.004903   

   Standard deviation of period  Fraction of locally unvoiced frames  \
0                      0.000460                               10.309   
1                      0.001895                               13.750   
2                      0.000712                               16.966   
3                      0.001401                                9.386   
4                      0.000097                               13.715   

   Number of voice breaks  Degree of voice breaks  
0                       0                   0.000  
1                       2                   1.429  
2                       4                   2.313  
3                       2                   3.946  
4                       0                   0.000  

[5 rows x 27 columns]

In [31]:
pred_data.shape

(11, 27)

In [17]:
pred_X = pred_data.iloc[:, 1:].values

In [42]:
pred_X[0]

array([4.540000e-03, 2.405700e-05, 2.680000e-03, 2.510000e-03,
       8.050000e-03, 2.804000e-02, 2.470000e-01, 1.478000e-02,
       1.741000e-02, 2.258000e-02, 4.434000e-02, 9.910670e-01,
       1.052600e-02, 2.341200e+01, 1.898940e+02, 1.883840e+02,
       1.235200e+01, 8.312000e+01, 1.994810e+02, 1.970000e+03,
       1.968000e+03, 5.304283e-03, 4.601280e-04, 1.030900e+01,
       0.000000e+00, 0.000000e+00])

In [32]:
pred_X = min_max_scaler.transform(pred_X)
pred_X

array([[-3.36254845e-01, -2.04327775e+03, -4.02003672e-01,
        -6.26348547e-01, -1.49083710e-01, -1.19543217e-01,
        -6.40039103e-01, -1.51202745e-01, -9.45200200e-02,
        -1.80278556e-01, -7.71714049e-02,  1.41112649e-01,
        -9.03836768e-01, -3.99543037e-02, -3.88469281e-01,
        -3.92771277e-01, -3.94556067e-03, -3.24329007e-01,
        -2.78154713e-01, -3.98055239e-02, -3.54773026e-02,
        -8.00179043e+01,  1.11531700e+02,  3.75848955e-02,
        -5.97510218e-02, -1.00524756e-02],
       [-3.37016674e-01, -2.77828130e+03, -4.03387821e-01,
        -6.27943926e-01, -1.49544998e-01, -1.19479612e-01,
        -3.39363084e-01, -1.51228459e-01, -9.44905503e-02,
        -1.80065335e-01, -7.71799763e-02,  4.67503248e-02,
        -8.83692627e-01, -3.08457581e-02, -3.87804860e-01,
        -3.94244948e-01,  8.60586159e-03, -3.23078295e-01,
        -2.77575409e-01, -4.01318020e-02, -3.58070343e-02,
        -3.62161452e+01,  1.82276525e+03,  5.48338861e-02,
         2.90

In [33]:
pred_y = svclassifier.predict(pred_X)
res = pd.DataFrame(pred_y)
res.columns = ["status"]
res.to_csv("SVC - Sri Lankan - optimized_mine3.csv")