In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE
from sklearn.linear_model import RidgeCV, LassoCV, Ridge, Lasso
from xgboost import XGBClassifier

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
data = pd.read_csv(r'Parkinsons Train Data.csv', header=0)
data.head()

Jitter(local)  Jitter(local, absolute)  ...  Degree of voice breaks  status
0          1.488                 0.000090  ...                   0.000       1
1          0.728                 0.000038  ...                   0.000       1
2          1.220                 0.000074  ...                   0.178       1
3          2.502                 0.000123  ...                   0.000       1
4          3.509                 0.000167  ...                  13.318       1

[5 rows x 27 columns]

In [3]:
X = data.iloc[:, :-1].values
X

array([[1.48800e+00, 9.02130e-05, 9.00000e-01, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [7.28000e-01, 3.76980e-05, 3.53000e-01, ..., 2.24700e+00,
        0.00000e+00, 0.00000e+00],
       [1.22000e+00, 7.40410e-05, 7.32000e-01, ..., 1.06560e+01,
        1.00000e+00, 1.78000e-01],
       ...,
       [2.91200e+00, 2.26205e-04, 1.14100e+00, ..., 2.00000e+01,
        1.00000e+00, 4.57400e+00],
       [3.78800e+00, 2.74883e-04, 1.78600e+00, ..., 1.66670e+01,
        3.00000e+00, 1.95750e+01],
       [1.80900e+00, 1.48510e-04, 6.80000e-01, ..., 1.81820e+01,
        1.00000e+00, 3.38700e+00]])

In [4]:
y = data.iloc[:, -1].values
y

array([1, 1, 1, ..., 0, 0, 0])

In [0]:
cols_11 = ['Jitter(local, absolute)','Shimmer (apq11)','AC', 'NDH', 'HTM',
       'Median Pitch', 'Mean Pitch', 'Standard deviation',
       'Minimum pitch', 'Maximum pitch', 'Number of pulses',
       'Number of periods', 'Mean period', 'Standard deviation of period',
       'Fraction of locally unvoiced frames', 'Number of voice breaks',
       'Degree of voice breaks']
data_11 = data[cols_11]

In [6]:
cols = list(data_11.columns)
model = XGBClassifier()
#Initializing RFE model
rfe = RFE(model)
#Transforming data using RFE
X_rfe = rfe.fit_transform(data_11,y)  
#Fitting the data to model
model.fit(X_rfe,y)
print(rfe.support_)
print(rfe.ranking_)
for i in range(17):
    print(cols[i], "----->", rfe.support_[i])

[ True  True False False  True  True False  True False False False  True
  True  True False False False]
[ 1  1  5  9  1  1  8  1  7  3  4  1  1  1  2 10  6]
Jitter(local, absolute) -----> True
Shimmer (apq11) -----> True
AC -----> False
NDH -----> False
HTM -----> True
Median Pitch -----> True
Mean Pitch -----> False
Standard deviation -----> True
Minimum pitch -----> False
Maximum pitch -----> False
Number of pulses -----> False
Number of periods -----> True
Mean period -----> True
Standard deviation of period -----> True
Fraction of locally unvoiced frames -----> False
Number of voice breaks -----> False
Degree of voice breaks -----> False


In [7]:
X = data_11.iloc[:, :].values
#no of features
nof_list=np.arange(1,30 )            
high_score=0
#Variable to store the optimum features
nof=0           
score_list =[]
for n in range(len(nof_list)):
    from sklearn.preprocessing import StandardScaler
    standard_X = StandardScaler()
    X = standard_X.fit_transform(X)
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 12)
    model = XGBClassifier()
    rfe = RFE(model,nof_list[n])
    X_train_rfe = rfe.fit_transform(X_train,y_train)
    X_test_rfe = rfe.transform(X_test)
    model.fit(X_train_rfe,y_train)
    score = model.score(X_test_rfe,y_test)
    score_list.append(score)
    if(score>high_score):
        high_score = score
        nof = nof_list[n]
print("Optimum number of features: %d" %nof)
print("Score with %d features: %f" % (nof, high_score))

Optimum number of features: 17
Score with 17 features: 0.745192


In [8]:
cols = list(data_11.columns)
model = XGBClassifier()
#Initializing RFE model
rfe = RFE(model, 17)             
#Transforming data using RFE
X_rfe = rfe.fit_transform(data_11,y)  
#Fitting the data to model
model.fit(X_rfe,y)              
temp = pd.Series(rfe.support_,index = cols)
selected_features_rfe = temp[temp==True].index
print(selected_features_rfe)

Index(['Jitter(local, absolute)', 'Shimmer (apq11)', 'AC', 'NDH', 'HTM',
       'Median Pitch', 'Mean Pitch', 'Standard deviation', 'Minimum pitch',
       'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period',
       'Standard deviation of period', 'Fraction of locally unvoiced frames',
       'Number of voice breaks', 'Degree of voice breaks'],
      dtype='object')


In [9]:
rfe_data = data[selected_features_rfe]
rfe_data

Jitter(local, absolute)  ...  Degree of voice breaks
0                    0.000090  ...                   0.000
1                    0.000038  ...                   0.000
2                    0.000074  ...                   0.178
3                    0.000123  ...                   0.000
4                    0.000167  ...                  13.318
...                       ...  ...                     ...
1031                 0.000398  ...                  15.113
1032                 0.000133  ...                  25.792
1033                 0.000226  ...                   4.574
1034                 0.000275  ...                  19.575
1035                 0.000149  ...                   3.387

[1036 rows x 17 columns]

In [10]:
X = rfe_data.iloc[:, :].values
X

array([[9.02130e-05, 6.80200e+00, 9.05905e-01, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [3.76980e-05, 7.19400e+00, 9.51285e-01, ..., 2.24700e+00,
        0.00000e+00, 0.00000e+00],
       [7.40410e-05, 7.54800e+00, 9.11508e-01, ..., 1.06560e+01,
        1.00000e+00, 1.78000e-01],
       ...,
       [2.26205e-04, 1.42390e+01, 8.83146e-01, ..., 2.00000e+01,
        1.00000e+00, 4.57400e+00],
       [2.74883e-04, 1.88180e+01, 7.65474e-01, ..., 1.66670e+01,
        3.00000e+00, 1.95750e+01],
       [1.48510e-04, 1.10730e+01, 9.25554e-01, ..., 1.81820e+01,
        1.00000e+00, 3.38700e+00]])

In [0]:
from sklearn.preprocessing import StandardScaler
standard_X = StandardScaler()
X = standard_X.fit_transform(X)

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 12)

In [13]:
model = XGBClassifier(learning_rate =0.05,
         n_estimators=250,
         max_depth=5,
         gamma=1,
         subsample=0.69,
         colsample_bytree=0.85)
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.85, gamma=1,
              learning_rate=0.05, max_delta_step=0, max_depth=5,
              min_child_weight=1, missing=None, n_estimators=250, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=0.69, verbosity=1)

In [14]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
y_pred = model.predict(X_test)

print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))
print("\n")

print("Classfications Results")
print(classification_report(y_test, y_pred))

print("Accuracy Score")
print(accuracy_score(y_test, y_pred))

from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = model, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Confusion Matrix
[[74 32]
 [23 79]]


Classfications Results
              precision    recall  f1-score   support

           0       0.76      0.70      0.73       106
           1       0.71      0.77      0.74       102

    accuracy                           0.74       208
   macro avg       0.74      0.74      0.74       208
weighted avg       0.74      0.74      0.74       208

Accuracy Score
0.7355769230769231
Accuracy: 68.72 %
Standard Deviation: 4.37 %


In [17]:
from sklearn.externals import joblib
joblib.dump(model, 'XGBoostmodel.pkl')
print("Model dumped!")

Model dumped!


In [20]:
model_columns = list(rfe_data.columns)
model_columns

['Jitter(local, absolute)',
 'Shimmer (apq11)',
 'AC',
 'NDH',
 'HTM',
 'Median Pitch',
 'Mean Pitch',
 'Standard deviation',
 'Minimum pitch',
 'Maximum pitch',
 'Number of pulses',
 'Number of periods',
 'Mean period',
 'Standard deviation of period',
 'Fraction of locally unvoiced frames',
 'Number of voice breaks',
 'Degree of voice breaks']

In [21]:
joblib.dump(model_columns, 'model_columns.pkl')
print("Models columns dumped!")

Models columns dumped!
