In [40]:
#importing the libraries needed for ML
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
plt.rc("font", size=14)
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

In [41]:
data = pd.read_csv(r'..\Datasets\Train Data with UPDRS_Only Vowels.csv', header = 0)
data.head()

Subject ID  Jitter(local)  Jitter(local, absolute)  Jitter (rap)  \
0           1          1.488                 0.000090         0.900   
1           1          0.728                 0.000038         0.353   
2           1          1.220                 0.000074         0.732   
3           2          0.427                 0.000034         0.243   
4           2          0.844                 0.000069         0.509   

   Jitter (ppq5)  Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  \
0          0.794         2.699            8.334                0.779   
1          0.376         1.059            5.864                0.642   
2          0.670         2.196            8.719                0.875   
3          0.249         0.728            7.428                0.694   
4          0.489         1.527           14.053                1.239   

   Shimmer (apq3)  Shimmer (apq5)  ...  Minimum pitch  Maximum pitch  \
0           4.517           4.609  ...        142.229        187.576   
1           2.058           3.180  ...        159.515        234.505   
2           4.347           5.166  ...        146.445        211.442   
3           4.205           4.311  ...        118.461        129.205   
4           6.131           7.015  ...        118.020        126.788   

   Number of pulses  Number of periods  Mean period  \
0               160                159     0.006065   
1               170                169     0.005181   
2              1431               1427     0.006071   
3               345                344     0.008073   
4               585                582     0.008174   

   Standard deviation of period  Fraction of locally unvoiced frames  \
0                      0.000416                                0.000   
1                      0.000403                                2.247   
2                      0.000474                               10.656   
3                      0.000143                                0.000   
4                      0.000123                                0.209   

   Number of voice breaks  Degree of voice breaks  status  
0                       0                   0.000       1  
1                       0                   0.000       1  
2                       1                   0.178       1  
3                       0                   0.000       1  
4                       2                   0.768       1  

[5 rows x 28 columns]

In [42]:
data.shape

(120, 28)

In [43]:
data.columns

Index(['Subject ID', 'Jitter(local)', 'Jitter(local, absolute)',
       'Jitter (rap)', 'Jitter (ppq5)', 'Jitter (ddp)', 'Shimmer (local)',
       'Shimmer (local, db)', 'Shimmer (apq3)', 'Shimmer (apq5)',
       'Shimmer (apq11)', 'Shimmer (dda)', 'AC', 'NDH', 'HTM', 'Median Pitch',
       'Mean Pitch', 'Standard deviation', 'Minimum pitch', 'Maximum pitch',
       'Number of pulses', 'Number of periods', 'Mean period',
       'Standard deviation of period', 'Fraction of locally unvoiced frames',
       'Number of voice breaks', 'Degree of voice breaks', 'status'],
      dtype='object')

In [44]:
#setting the dependent variable
y = data.iloc[:, -1].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [45]:
X = data.iloc[:, 1:-1].values
X

array([[1.48800e+00, 9.02130e-05, 9.00000e-01, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [7.28000e-01, 3.76980e-05, 3.53000e-01, ..., 2.24700e+00,
        0.00000e+00, 0.00000e+00],
       [1.22000e+00, 7.40410e-05, 7.32000e-01, ..., 1.06560e+01,
        1.00000e+00, 1.78000e-01],
       ...,
       [4.71000e-01, 3.38370e-05, 1.86000e-01, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [4.31900e+00, 3.17122e-04, 2.77400e+00, ..., 2.91300e+00,
        1.00000e+00, 7.03800e+00],
       [1.54300e+00, 1.03357e-04, 1.00400e+00, ..., 3.51000e-01,
        0.00000e+00, 0.00000e+00]])

In [46]:
X[5].size

26

In [47]:
from sklearn.preprocessing import StandardScaler
standard_X = StandardScaler()
standard_scaled_X = standard_X.fit_transform(X)
standard_scaled_X

array([[ 0.95200109,  0.84480825,  1.09023877, ..., -0.49321641,
        -0.35850613, -0.26520441],
       [-0.14968145, -0.32962626, -0.2011674 , ..., -0.09898599,
        -0.35850613, -0.26520441],
       [ 0.56351303,  0.48314102,  0.69360945, ...,  1.37635161,
         0.69078011, -0.22328107],
       ...,
       [-0.5222241 , -0.41597286, -0.59543583, ..., -0.49321641,
        -0.35850613, -0.26520441],
       [ 5.05576855,  5.91935384,  5.51454435, ...,  0.01786201,
         0.69078011,  1.39241639],
       [ 1.03172811,  1.13875793,  1.3357712 , ..., -0.43163435,
        -0.35850613, -0.26520441]])

In [48]:
def standardScale(X):
    X = standard_X.transform(X)
    return X

In [49]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
minmax_scaled_X = min_max_scaler.fit_transform(X)
minmax_scaled_X

array([[0.31436183, 0.26951295, 0.30899705, ..., 0.        , 0.        ,
        0.        ],
       [0.13029789, 0.10045167, 0.10730088, ..., 0.0642    , 0.        ,
        0.        ],
       [0.24945507, 0.21745051, 0.24705015, ..., 0.30445714, 0.16666667,
        0.00674702],
       ...,
       [0.06805522, 0.08802197, 0.04572271, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 1.        , ..., 0.08322857, 0.16666667,
        0.2667728 ],
       [0.32768225, 0.31182737, 0.34734513, ..., 0.01002857, 0.        ,
        0.        ]])

In [50]:
def minmaxScale(X):
    X = min_max_scaler.transform(X)
    return X

In [51]:
data.columns

Index(['Subject ID', 'Jitter(local)', 'Jitter(local, absolute)',
       'Jitter (rap)', 'Jitter (ppq5)', 'Jitter (ddp)', 'Shimmer (local)',
       'Shimmer (local, db)', 'Shimmer (apq3)', 'Shimmer (apq5)',
       'Shimmer (apq11)', 'Shimmer (dda)', 'AC', 'NDH', 'HTM', 'Median Pitch',
       'Mean Pitch', 'Standard deviation', 'Minimum pitch', 'Maximum pitch',
       'Number of pulses', 'Number of periods', 'Mean period',
       'Standard deviation of period', 'Fraction of locally unvoiced frames',
       'Number of voice breaks', 'Degree of voice breaks', 'status'],
      dtype='object')

In [52]:
fixed_cols = ['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods',
              'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks']
jitter_cols = ['Jitter(local)', 'Jitter(local, absolute)', 'Jitter (rap)','Jitter (ppq5)', 'Jitter (ddp)']
shimmer_cols = ['Shimmer (local)', 'Shimmer (local, db)', 'Shimmer (apq3)', 'Shimmer (apq5)', 'Shimmer (apq11)',
                'Shimmer (dda)']
pitch_cols = ['Median Pitch', 'Mean Pitch']

In [53]:
def getXGBoost(X, y):
    
    from sklearn.model_selection import train_test_split
    from sklearn.metrics import accuracy_score
    X_train, X_test, Y_train, Y_test = train_test_split(X, y, random_state=12, test_size = 0.2)
    # Train
    from xgboost import XGBClassifier
    model = XGBClassifier()
    model.fit(X_train, Y_train)

    # Evaluate
    print("Accuracy for training set -> ", end = "")
    Y_hat = [round(yhat) for yhat in model.predict(X)]
    print(accuracy_score(y, Y_hat)) # Full set accuracy
    Y_hat = [round(yhat) for yhat in model.predict(X_test)]
    print("Accuracy for test set -> ", end = "")
    print(accuracy_score(Y_test, Y_hat)) # Test set accuracy

    #Validations
    y_pred = model.predict(X_test)

    #Confusion Matrix
    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(Y_test, y_pred) # Calulate Confusion matrix for test set.
    print(cm)

    from sklearn.model_selection import cross_val_score
    accuracies = cross_val_score(estimator = model, X = X_train, y = Y_train, cv = 10)
    print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
    print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [54]:
for jitter in jitter_cols:
    for shimmer in shimmer_cols:
        for pitch in pitch_cols:
            
            fixed_cols.append(jitter)
            fixed_cols.append(shimmer)
            fixed_cols.append(pitch)
            print(fixed_cols)
            print("\n")
            print("Added columns to the dataset are:", jitter, shimmer, pitch)
            print("\n")
            X = data[fixed_cols].values
            print("---------Standard Scaled---------")
            print("\n")
            standard_X = StandardScaler()
            standard_scaled_X = standard_X.fit_transform(X)
            standard_scaled_X
            getXGBoost(standard_scaled_X, y)
            print("\n")
            print("---------MinMax Scaled---------")
            print("\n")
            min_max_scaler = preprocessing.MinMaxScaler()
            minmax_scaled_X = min_max_scaler.fit_transform(X)
            minmax_scaled_X
            getXGBoost(minmax_scaled_X, y)
            fixed_cols.remove(jitter)
            fixed_cols.remove(shimmer)
            fixed_cols.remove(pitch)
            print("\n")

['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter(local)', 'Shimmer (local)', 'Median Pitch']


Added columns to the dataset are: Jitter(local) Shimmer (local) Median Pitch


---------Standard Scaled---------


Accuracy for training set -> 0.925
Accuracy for test set -> 0.625
[[ 4  5]
 [ 4 11]]
Accuracy: 67.56 %
Standard Deviation: 10.37 %


---------MinMax Scaled---------


Accuracy for training set -> 0.925
Accuracy for test set -> 0.625
[[ 4  5]
 [ 4 11]]
Accuracy: 67.56 %
Standard Deviation: 10.37 %


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter(local)', 'Shimmer (local)', 'Mean Pitch']


Added columns to the dataset are: Jitter(local) Shimmer (local) Mean Pitch


Accuracy: 67.67 %
Standard Deviation: 12.40 %


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter(local, absolute)', 'Shimmer (local)', 'Median Pitch']


Added columns to the dataset are: Jitter(local, absolute) Shimmer (local) Median Pitch


---------Standard Scaled---------


Accuracy for training set -> 0.9333333333333333
Accuracy for test set -> 0.6666666666666666
[[ 6  3]
 [ 5 10]]
Accuracy: 69.67 %
Standard Deviation: 11.79 %


---------MinMax Scaled---------


Accuracy for training set -> 0.9333333333333333
Accuracy for test set -> 0.6666666666666666
[[ 6  3]
 [ 5 10]]
Accuracy: 69.67 %
Standard Deviation: 11.79 %


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter

Accuracy: 67.78 %
Standard Deviation: 11.36 %


---------MinMax Scaled---------


Accuracy for training set -> 0.9333333333333333
Accuracy for test set -> 0.6666666666666666
[[ 6  3]
 [ 5 10]]
Accuracy: 67.78 %
Standard Deviation: 11.36 %


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter (rap)', 'Shimmer (local)', 'Median Pitch']


Added columns to the dataset are: Jitter (rap) Shimmer (local) Median Pitch


---------Standard Scaled---------


Accuracy for training set -> 0.925
Accuracy for test set -> 0.625
[[ 4  5]
 [ 4 11]]
Accuracy: 70.89 %
Standard Deviation: 7.32 %


---------MinMax Scaled---------


Accuracy for training set -> 0.925
Accuracy for test set -> 0.625
[[ 4  5]
 [ 4 11]]
Accuracy: 70.89 %
Standard Deviation: 7.32 %


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of period

Accuracy: 66.78 %
Standard Deviation: 10.44 %


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter (ppq5)', 'Shimmer (local)', 'Median Pitch']


Added columns to the dataset are: Jitter (ppq5) Shimmer (local) Median Pitch


---------Standard Scaled---------


Accuracy for training set -> 0.925
Accuracy for test set -> 0.625
[[ 4  5]
 [ 4 11]]
Accuracy: 70.78 %
Standard Deviation: 9.94 %


---------MinMax Scaled---------


Accuracy for training set -> 0.925
Accuracy for test set -> 0.625
[[ 4  5]
 [ 4 11]]
Accuracy: 70.78 %
Standard Deviation: 9.94 %


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter (ppq5)', 'Shimmer (local)', 'Mean Pitch']


Added columns to the dataset 

Accuracy: 70.89 %
Standard Deviation: 7.32 %


---------MinMax Scaled---------


Accuracy for training set -> 0.925
Accuracy for test set -> 0.625
[[ 4  5]
 [ 4 11]]
Accuracy: 70.89 %
Standard Deviation: 7.32 %


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of locally unvoiced frames', 'Number of voice breaks', 'Degree of voice breaks', 'Jitter (ddp)', 'Shimmer (local)', 'Mean Pitch']


Added columns to the dataset are: Jitter (ddp) Shimmer (local) Mean Pitch


---------Standard Scaled---------


Accuracy for training set -> 0.925
Accuracy for test set -> 0.625
[[ 4  5]
 [ 4 11]]
Accuracy: 68.67 %
Standard Deviation: 9.35 %


---------MinMax Scaled---------


Accuracy for training set -> 0.925
Accuracy for test set -> 0.625
[[ 4  5]
 [ 4 11]]
Accuracy: 68.67 %
Standard Deviation: 9.35 %


['AC', 'NDH', 'HTM', 'Minimum pitch', 'Maximum pitch', 'Number of pulses', 'Number of periods', 'Mean period', 'Fraction of 

In [ ]:
fixed_cols

In [ ]:
getXGBoost(minmax_scaled_X, y)

In [ ]:
getXGBoost(standard_scaled_X, y)

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train, X_test, Y_train, Y_test = train_test_split(X, y, random_state=12, test_size = 0.1)

In [19]:
# Train
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(X_train, Y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [20]:
X_train

array([[6.0500e-01, 4.1830e-05, 3.0100e-01, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [2.9100e-01, 1.2654e-05, 1.5900e-01, ..., 2.0410e+00, 0.0000e+00,
        0.0000e+00],
       [5.2600e-01, 3.6626e-05, 2.9100e-01, ..., 9.1700e-01, 0.0000e+00,
        0.0000e+00],
       ...,
       [1.4930e+00, 6.3766e-05, 9.1200e-01, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [8.8800e-01, 9.2367e-05, 3.5200e-01, ..., 5.4550e+00, 0.0000e+00,
        0.0000e+00],
       [7.9200e-01, 5.9694e-05, 4.7200e-01, ..., 3.2410e+00, 1.0000e+00,
        2.3320e+00]])

In [21]:
X_test

array([[1.005000e+00, 6.467800e-05, 3.980000e-01, 3.600000e-01,
        1.194000e+00, 3.638000e+00, 4.590000e-01, 1.598000e+00,
        2.181000e+00, 3.461000e+00, 4.795000e+00, 9.667370e-01,
        5.365100e-02, 2.302100e+01, 1.559200e+02, 1.552690e+02,
        6.935000e+00, 1.373470e+02, 1.676420e+02, 1.490000e+02,
        1.480000e+02, 6.433842e-03, 3.309520e-04, 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [1.091000e+00, 5.923700e-05, 6.550000e-01, 5.530000e-01,
        1.965000e+00, 1.604600e+01, 1.363000e+00, 8.314000e+00,
        1.320300e+01, 1.105400e+01, 2.494200e+01, 8.719330e-01,
        1.696490e-01, 9.316000e+00, 1.813830e+02, 1.841720e+02,
        1.071800e+01, 1.706120e+02, 2.555940e+02, 2.850000e+02,
        2.840000e+02, 5.429971e-03, 3.046050e-04, 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [2.960000e-01, 2.033100e-05, 9.800000e-02, 1.330000e-01,
        2.930000e-01, 3.022000e+00, 2.880000e-01, 1.164000e+00,
        1.529000e+00, 2.996000

In [55]:
y_train_pred = model.predict(X_train)

In [22]:
y_pred = model.predict(X_test)

In [23]:
y_pred

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1], dtype=int64)

In [24]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred) # Calulate Confusion matrix for test set.
print(cm)

[[2 3]
 [1 6]]


In [56]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_train, y_train_pred) # Calulate Confusion matrix for test set.
print(cm)

[[55  0]
 [ 0 53]]


In [25]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = model, X = X_train, y = Y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 69.55 %
Standard Deviation: 9.25 %


In [35]:
pred_data = pd.read_csv(r'..\Datasets\Parkinsons Test Data.csv', header = 0)
pred_data.head()

Jitter(local)  Jitter(local, absolute)  Jitter (rap)  Jitter (ppq5)  \
0          0.135                 0.000007         0.067          0.078   
1          0.143                 0.000007         0.073          0.081   
2          0.162                 0.000008         0.087          0.089   
3          0.140                 0.000007         0.075          0.089   
4          0.150                 0.000007         0.080          0.097   

   Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  Shimmer (apq3)  \
0         0.202            2.033                0.178           1.074   
1         0.219            1.236                0.107           0.612   
2         0.260            1.338                0.117           0.630   
3         0.224            1.086                0.094           0.556   
4         0.240            1.049                0.091           0.533   

   Shimmer (apq5)  Shimmer (apq11)  ...  Standard deviation  Minimum pitch  \
0           1.336            1.576  ...               0.859        184.502   
1           0.904            0.894  ...               0.755        198.665   
2           0.948            1.017  ...               1.860        197.220   
3           0.747            0.823  ...               0.931        202.324   
4           0.698            0.777  ...               0.880        205.407   

   Maximum pitch  Number of pulses  Number of periods  Mean period  \
0        187.880               183                182     0.005368   
1        202.214               194                193     0.004988   
2        206.060               198                197     0.004940   
3        206.182               200                199     0.004900   
4        209.927               204                203     0.004820   

   Standard deviation of period  Fraction of locally unvoiced frames  \
0                      0.000025                                  0.0   
1                      0.000020                                  0.0   
2                      0.000046                                  0.0   
3                      0.000023                                  0.0   
4                      0.000022                                  0.0   

   Number of voice breaks  Degree of voice breaks  
0                       0                     0.0  
1                       0                     0.0  
2                       0                     0.0  
3                       0                     0.0  
4                       0                     0.0  

[5 rows x 26 columns]

In [31]:
pred_data.shape

(169, 26)

In [32]:
pred_X = pred_data.iloc[:, :].values

In [33]:
pred_X = standard_X.transform(pred_X)
pred_X

array([[-1.00928375, -1.0094408 , -0.87638159, ..., -0.49321641,
        -0.35850613, -0.26520441],
       [-0.99768709, -1.01391356, -0.86221626, ..., -0.49321641,
        -0.35850613, -0.26520441],
       [-0.97014503, -0.99378614, -0.82916382, ..., -0.49321641,
        -0.35850613, -0.26520441],
       ...,
       [-0.53237118, -0.48612807, -0.57418783, ..., -0.49321641,
        -0.35850613, -0.26520441],
       [-0.51787535, -0.48612807, -0.61196205, ..., -0.49321641,
        -0.35850613, -0.26520441],
       [-1.18184202, -1.14566111, -1.01775161, ...,  3.49417776,
         2.78935258,  7.12084112]])

In [34]:
pred_y = model.predict(pred_X)
res = pd.DataFrame(pred_y)
res.columns = ["status"]
res.to_csv("XGBoost - predictions 2.csv")