In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

In [6]:
data = pd.read_csv(r'..\Datasets\Parkinsons Processed Training - Only Vowels - Sri Lankan.csv', header = 0)
data.head()

Subject Id  Jitter(local)  Jitter(local, absolute)  Jitter (rap)  \
0           1        0.01488                 0.000090       0.00900   
1           1        0.00728                 0.000038       0.00353   
2           1        0.00472                 0.000031       0.00224   
3           2        0.00427                 0.000034       0.00243   
4           2        0.00844                 0.000069       0.00509   

   Jitter (ppq5)  Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  \
0        0.00794       0.02699          0.08334                0.779   
1        0.00376       0.01059          0.05864                0.642   
2        0.00245       0.00673          0.06404                0.629   
3        0.00249       0.00728          0.07428                0.694   
4        0.00489       0.01527          0.14053                1.239   

   Shimmer (apq3)  Shimmer (apq5)  ...  Maximum pitch  Number of pulses  \
0         0.04517         0.04609  ...        187.576               160   
1         0.02058         0.03180  ...        234.505               170   
2         0.03434         0.03765  ...        190.019               675   
3         0.04205         0.04311  ...        129.205               345   
4         0.06131         0.07015  ...        126.788               585   

   Number of periods  Mean period  Standard deviation of period  \
0                159     0.006065                      0.000416   
1                169     0.005181                      0.000403   
2                673     0.006649                      0.000132   
3                344     0.008073                      0.000143   
4                582     0.008174                      0.000123   

   Fraction of locally unvoiced frames  Number of voice breaks  \
0                              0.00000                       0   
1                              0.02247                       0   
2                              0.26180                       1   
3                              0.00000                       0   
4                              0.00209                       2   

   Degree of voice breaks  UPDRS  status  
0                 0.00000     23       1  
1                 0.00000     23       1  
2                 0.26325     23       1  
3                 0.00000      8       1  
4                 0.00768      8       1  

[5 rows x 29 columns]

In [7]:
data.shape

(120, 29)

In [8]:
X = data.iloc[:, 1:24].values
X

array([[1.488000e-02, 9.021300e-05, 9.000000e-03, ..., 1.590000e+02,
        6.064725e-03, 4.162760e-04],
       [7.280000e-03, 3.769800e-05, 3.530000e-03, ..., 1.690000e+02,
        5.181253e-03, 4.034940e-04],
       [4.720000e-03, 3.137300e-05, 2.240000e-03, ..., 6.730000e+02,
        6.649119e-03, 1.321080e-04],
       ...,
       [4.710000e-03, 3.383700e-05, 1.860000e-03, ..., 1.750000e+02,
        7.178780e-03, 1.298030e-04],
       [4.319000e-02, 3.171220e-04, 2.774000e-02, ..., 2.560000e+02,
        7.342534e-03, 3.119150e-04],
       [1.543000e-02, 1.033570e-04, 1.004000e-02, ..., 4.250000e+02,
        6.700038e-03, 1.082910e-04]])

In [9]:
y = data.iloc[:, -1].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, random_state=12, test_size = 0.2)

In [11]:
standard_X = StandardScaler()
X_train = standard_X.fit_transform(X_train)
X_test = standard_X.transform(X_test)

In [12]:
training_accuracy = []
test_accuracy = []
# try n_neighbors from 1 to 100
neighbors_settings = range(1, 40)
index = 0
max_accuracy = 0

for n_neighbors in neighbors_settings:
    # build the model
    knn = KNeighborsClassifier(n_neighbors=n_neighbors)
    knn.fit(X_train, Y_train)
    # record training set accuracy
    training_accuracy.append(knn.score(X_train, Y_train))
    # record test set accuracy
    accuracy = knn.score(X_test, Y_test)
    test_accuracy.append(accuracy)
    if(accuracy > max_accuracy):
        max_accuracy = accuracy
        index = n_neighbors

print("Best Accuracy:", max_accuracy)
print("N_neighbors: ", index)

Best Accuracy: 0.6666666666666666
N_neighbors:  5


In [13]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [14]:
y_pred = model.predict(X_test)

In [15]:
cm = confusion_matrix(Y_test, y_pred) # Calulate Confusion matrix for test set.
print(cm)

[[7 2]
 [6 9]]


In [16]:
accuracies = cross_val_score(estimator = model, X = X_train, y = Y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 51.11 %
Standard Deviation: 16.71 %


In [17]:
data_test = pd.read_csv(r'../Datasets/Sri Lankan Dataset.csv', header = 0)
data_test.head()

Subject ID  Jitter(local)  Jitter(local, absolute)  Jitter (rap)  \
0          17        0.01119                 0.000085       0.00387   
1          17        0.01001                 0.000071       0.00314   
2          17        0.00576                 0.000043       0.00221   
3          17        0.01288                 0.000104       0.00559   
4          17        0.00784                 0.000060       0.00243   

   Jitter (ppq5)  Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  \
0        0.00433       0.01160          0.04168                0.490   
1        0.00416       0.00943          0.03785                0.493   
2        0.00289       0.00663          0.03913                0.439   
3        0.00603       0.01677          0.04783                0.502   
4        0.00314       0.00729          0.03155                0.431   

   Shimmer (apq3)  Shimmer (apq5)  ...  Standard deviation  Minimum pitch  \
0         0.01733         0.02246  ...              34.427         96.944   
1         0.01256         0.02010  ...              39.380        104.679   
2         0.01367         0.01944  ...               4.531        123.548   
3         0.02122         0.02702  ...               3.448        107.007   
4         0.01156         0.01636  ...              18.480        109.714   

   Maximum pitch  Number of pulses  Number of periods  Mean period  \
0        254.919               142                141      0.00762   
1        247.911               180                178      0.00710   
2        142.684               139                138      0.00753   
3        133.246               120                119      0.00804   
4        252.798               162                161      0.00769   

   Standard deviation of period  Fraction of locally unvoiced frames  \
0                      0.001520                              0.73839   
1                      0.001670                              0.62000   
2                      0.000260                              0.67122   
3                      0.000270                              0.67381   
4                      0.000826                              0.56169   

   Number of voice breaks  Degree of voice breaks  
0                       0                 0.00000  
1                       1                 0.06049  
2                       0                 0.00000  
3                       0                 0.00000  
4                       0                 0.00000  

[5 rows x 27 columns]

In [18]:
testing_X = data_test.iloc[:, 1:24].values
testing_X

array([[1.119000e-02, 8.520000e-05, 3.870000e-03, ..., 1.410000e+02,
        7.620000e-03, 1.520000e-03],
       [1.001000e-02, 7.110000e-05, 3.140000e-03, ..., 1.780000e+02,
        7.100000e-03, 1.670000e-03],
       [5.760000e-03, 4.330000e-05, 2.210000e-03, ..., 1.380000e+02,
        7.530000e-03, 2.600000e-04],
       ...,
       [4.670000e-03, 2.450600e-05, 2.430000e-03, ..., 1.640000e+02,
        5.249619e-03, 1.654250e-04],
       [4.680000e-03, 2.411200e-05, 1.840000e-03, ..., 1.350000e+02,
        5.155909e-03, 4.772440e-04],
       [3.960000e-03, 1.769700e-05, 1.460000e-03, ..., 1.650000e+02,
        4.471620e-03, 1.680530e-04]])

In [19]:
testing_X = standard_X.transform(testing_X)
testing_X

array([[ 0.37400024,  0.64550224, -0.13238182, ..., -0.76528168,
         0.75775007,  2.9031042 ],
       [ 0.21239995,  0.35239873, -0.2958588 , ..., -0.64298535,
         0.45615794,  3.28381009],
       [-0.36963498, -0.22549331, -0.50412398, ..., -0.77519759,
         0.70555143, -0.29482525],
       ...,
       [-0.51890982, -0.61617326, -0.45485695, ..., -0.68925963,
        -0.61703505, -0.53486031],
       [-0.51754033, -0.62436353, -0.58698217, ..., -0.78511351,
        -0.67138543,  0.25654855],
       [-0.61614389, -0.75771524, -0.67207978, ..., -0.68595433,
        -1.06826269, -0.52819034]])

In [20]:
y_predict_test = model.predict(testing_X)

In [21]:
y_predict_test

array([1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [22]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, random_state=12, test_size = 0.2)

In [23]:
min_max_scaler = preprocessing.MinMaxScaler()
X_train = min_max_scaler.fit_transform(X_train)
X_test = min_max_scaler.transform(X_test)

In [24]:
training_accuracy = []
test_accuracy = []
# try n_neighbors from 1 to 100
neighbors_settings = range(1, 40)
index = 0
max_accuracy = 0

for n_neighbors in neighbors_settings:
    # build the model
    knn = KNeighborsClassifier(n_neighbors=n_neighbors)
    knn.fit(X_train, Y_train)
    # record training set accuracy
    training_accuracy.append(knn.score(X_train, Y_train))
    # record test set accuracy
    accuracy = knn.score(X_test, Y_test)
    test_accuracy.append(accuracy)
    if(accuracy > max_accuracy):
        max_accuracy = accuracy
        index = n_neighbors

print("Best Accuracy:", max_accuracy)
print("N_neighbors: ", index)

Best Accuracy: 0.6666666666666666
N_neighbors:  3


In [25]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [26]:
testing_X = data_test.iloc[:, 1:24].values
testing_X

array([[1.119000e-02, 8.520000e-05, 3.870000e-03, ..., 1.410000e+02,
        7.620000e-03, 1.520000e-03],
       [1.001000e-02, 7.110000e-05, 3.140000e-03, ..., 1.780000e+02,
        7.100000e-03, 1.670000e-03],
       [5.760000e-03, 4.330000e-05, 2.210000e-03, ..., 1.380000e+02,
        7.530000e-03, 2.600000e-04],
       ...,
       [4.670000e-03, 2.450600e-05, 2.430000e-03, ..., 1.640000e+02,
        5.249619e-03, 1.654250e-04],
       [4.680000e-03, 2.411200e-05, 1.840000e-03, ..., 1.350000e+02,
        5.155909e-03, 4.772440e-04],
       [3.960000e-03, 1.769700e-05, 1.460000e-03, ..., 1.650000e+02,
        4.471620e-03, 1.680530e-04]])

In [27]:
testing_X = min_max_scaler.transform(testing_X)
testing_X

array([[0.22499395, 0.25337463, 0.11983776, ..., 0.05931612, 0.6223364 ,
        0.65096152],
       [0.1964156 , 0.20798256, 0.09292035, ..., 0.08513608, 0.55299668,
        0.71762866],
       [0.09348511, 0.11848616, 0.05862832, ..., 0.05722261, 0.6103353 ,
        0.09095754],
       ...,
       [0.06708646, 0.05798273, 0.06674041, ..., 0.07536636, 0.30625648,
        0.0489239 ],
       [0.06732865, 0.05671432, 0.04498525, ..., 0.0551291 , 0.29376067,
        0.18751111],
       [0.04989101, 0.03606254, 0.03097345, ..., 0.0760642 , 0.20251372,
        0.05009191]])

In [28]:
y_testing_pred = model.predict(testing_X)

In [29]:
y_testing_pred

array([0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0], dtype=int64)

In [30]:
y_testing_pred.size

60

In [31]:
total = 0
for i in y_testing_pred:
    total = total + i
    
print(total)

27
