In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score

In [2]:
data = pd.read_csv(r'..\Datasets\Parkinsons Processed Training - Only Vowels - Sri Lankan.csv', header = 0)
data.head()

Subject Id  Jitter(local)  Jitter(local, absolute)  Jitter (rap)  \
0           1        0.01488                 0.000090       0.00900   
1           1        0.00728                 0.000038       0.00353   
2           1        0.00472                 0.000031       0.00224   
3           2        0.00427                 0.000034       0.00243   
4           2        0.00844                 0.000069       0.00509   

   Jitter (ppq5)  Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  \
0        0.00794       0.02699          0.08334                0.779   
1        0.00376       0.01059          0.05864                0.642   
2        0.00245       0.00673          0.06404                0.629   
3        0.00249       0.00728          0.07428                0.694   
4        0.00489       0.01527          0.14053                1.239   

   Shimmer (apq3)  Shimmer (apq5)  ...  Maximum pitch  Number of pulses  \
0         0.04517         0.04609  ...        187.576               160   
1         0.02058         0.03180  ...        234.505               170   
2         0.03434         0.03765  ...        190.019               675   
3         0.04205         0.04311  ...        129.205               345   
4         0.06131         0.07015  ...        126.788               585   

   Number of periods  Mean period  Standard deviation of period  \
0                159     0.006065                      0.000416   
1                169     0.005181                      0.000403   
2                673     0.006649                      0.000132   
3                344     0.008073                      0.000143   
4                582     0.008174                      0.000123   

   Fraction of locally unvoiced frames  Number of voice breaks  \
0                              0.00000                       0   
1                              0.02247                       0   
2                              0.26180                       1   
3                              0.00000                       0   
4                              0.00209                       2   

   Degree of voice breaks  UPDRS  status  
0                 0.00000     23       1  
1                 0.00000     23       1  
2                 0.26325     23       1  
3                 0.00000      8       1  
4                 0.00768      8       1  

[5 rows x 29 columns]

In [3]:
data.shape

(120, 29)

In [5]:
X_table = data.iloc[:, 1:24]

In [6]:
X_table

Jitter(local)  Jitter(local, absolute)  Jitter (rap)  Jitter (ppq5)  \
0          0.01488                 0.000090       0.00900        0.00794   
1          0.00728                 0.000038       0.00353        0.00376   
2          0.00472                 0.000031       0.00224        0.00245   
3          0.00427                 0.000034       0.00243        0.00249   
4          0.00844                 0.000069       0.00509        0.00489   
..             ...                      ...           ...            ...   
115        0.00601                 0.000031       0.00316        0.00339   
116        0.00382                 0.000017       0.00169        0.00203   
117        0.00471                 0.000034       0.00186        0.00230   
118        0.04319                 0.000317       0.02774        0.01708   
119        0.01543                 0.000103       0.01004        0.00648   

     Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  Shimmer (apq3)  \
0         0.02699          0.08334                0.779         0.04517   
1         0.01059          0.05864                0.642         0.02058   
2         0.00673          0.06404                0.629         0.03434   
3         0.00728          0.07428                0.694         0.04205   
4         0.01527          0.14053                1.239         0.06131   
..            ...              ...                  ...             ...   
115       0.00947          0.07492                0.681         0.03729   
116       0.00508          0.06905                0.648         0.02728   
117       0.00558          0.02793                0.260         0.01183   
118       0.08322          0.13924                1.195         0.08558   
119       0.03012          0.17447                1.694         0.11171   

     Shimmer (apq5)  Shimmer (apq11)  ...     HTM  Median Pitch  Mean Pitch  \
0           0.04609          0.06802  ...  11.130       166.533     164.781   
1           0.03180          0.07194  ...  17.403       195.252     193.289   
2           0.03765          0.05138  ...  17.809       150.215     150.379   
3           0.04311          0.05250  ...  15.267       124.171     123.883   
4           0.07015          0.09260  ...  10.747       122.220     122.381   
..              ...              ...  ...     ...           ...         ...   
115         0.04581          0.06352  ...  16.770       202.463     193.859   
116         0.03968          0.06920  ...  19.500       221.165     222.804   
117         0.01520          0.02576  ...  22.797       138.697     139.265   
118         0.06036          0.08585  ...  12.266       136.805     136.026   
119         0.06851          0.09395  ...  16.199       149.185     149.272   

     Standard deviation  Minimum pitch  Maximum pitch  Number of pulses  \
0                10.421        142.229        187.576               160   
1                14.773        159.515        234.505               170   
2                 3.027        141.083        190.019               675   
3                 2.179        118.461        129.205               345   
4                 1.650        118.020        126.788               585   
..                  ...            ...            ...               ...   
115              28.380         99.593        214.486               215   
116               6.486        205.108        237.431               188   
117               2.273        132.744        145.840               176   
118               4.846        124.543        165.029               258   
119               1.886        141.443        158.612               426   

     Number of periods  Mean period  Standard deviation of period  
0                  159     0.006065                      0.000416  
1                  169     0.005181                      0.000403  
2                  673     0.006649                      0.000132  
3                  344     0.008073                      0.000143  
4

In [7]:
X = data.iloc[:, 1:24].values
X

array([[1.488000e-02, 9.021300e-05, 9.000000e-03, ..., 1.590000e+02,
        6.064725e-03, 4.162760e-04],
       [7.280000e-03, 3.769800e-05, 3.530000e-03, ..., 1.690000e+02,
        5.181253e-03, 4.034940e-04],
       [4.720000e-03, 3.137300e-05, 2.240000e-03, ..., 6.730000e+02,
        6.649119e-03, 1.321080e-04],
       ...,
       [4.710000e-03, 3.383700e-05, 1.860000e-03, ..., 1.750000e+02,
        7.178780e-03, 1.298030e-04],
       [4.319000e-02, 3.171220e-04, 2.774000e-02, ..., 2.560000e+02,
        7.342534e-03, 3.119150e-04],
       [1.543000e-02, 1.033570e-04, 1.004000e-02, ..., 4.250000e+02,
        6.700038e-03, 1.082910e-04]])

In [8]:
y = data.iloc[:, -1].values

In [9]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [10]:
y.size

120

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, random_state=12, test_size = 0.05)

In [13]:
standard_X = StandardScaler()
X_train = standard_X.fit_transform(X_train)
X_test = standard_X.transform(X_test)

In [14]:
X_train

array([[-0.47582385, -0.25413313, -0.66856381, ..., -0.69276098,
         1.18547244,  0.65223381],
       [-0.11928969, -0.30568555, -0.16953713, ..., -0.67933618,
        -0.66592172,  0.06844739],
       [-0.50191171, -0.48906679, -0.6425482 , ..., -0.21282432,
         0.02572184,  1.17282677],
       ...,
       [-0.05696868, -0.10989273, -0.1340613 , ..., -0.21618052,
        -0.15667352,  0.1624282 ],
       [ 0.11260245,  0.90597372, -0.17190218, ..., -0.91762641,
         2.43736423,  1.04568876],
       [-0.02653283,  0.18182396,  0.11190446, ...,  0.62958198,
         0.73221524, -0.6968619 ]])

In [15]:
X_test

array([[ 0.28217357,  0.2922871 , -0.06310964, -0.17417162, -0.06304857,
        -0.75331427, -0.55445741, -0.76528054, -0.66609614, -0.69003663,
        -0.76516922,  0.3084593 , -0.20324423,  1.01284909, -0.29396213,
        -0.33844259, -0.24005009, -0.2433175 , -0.4904014 , -0.75513068,
        -0.74981639,  0.07876344, -0.11943653],
       [ 0.4068156 ,  0.17169521,  0.5447096 ,  0.34834323,  0.54471531,
         1.68874841,  1.54504888,  1.61263962,  2.34292106,  1.35454907,
         1.6126087 , -0.95016882,  0.7269022 , -1.40614805,  0.23924838,
         0.25966106, -0.03626776,  0.43902381,  0.51139016, -0.29867834,
        -0.29337313, -0.5180547 , -0.18767531],
       [-0.74539846, -0.69059998, -0.77262625, -0.78873571, -0.77328885,
        -0.87455142, -0.95159854, -0.91894602, -0.8440928 , -0.81524832,
        -0.91906917,  0.66749836, -0.57697709,  1.51429899, -0.48831184,
        -0.54080413, -0.43537516, -0.23933811, -0.63039845, -0.76519948,
        -0.75988499,  0.3363

In [16]:
model = LogisticRegression()

In [17]:
model.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [18]:
y_pred = model.predict(X_test)

In [19]:
cm = confusion_matrix(Y_test, y_pred) # Calulate Confusion matrix for test set.
print(cm)

[[3 0]
 [2 1]]


In [20]:
print(accuracy_score(Y_test, y_pred))

0.6666666666666666


In [21]:
accuracies = cross_val_score(estimator = model, X = X_train, y = Y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 58.86 %
Standard Deviation: 22.56 %


In [24]:
data_test = pd.read_csv(r'../Datasets/Sri Lankan Dataset - Finalised.csv', header = 0)
data_test.head()

Subject ID  Jitter(local)  Jitter(local, absolute)  Jitter (rap)  \
0          16       0.014680                 0.000086       0.00510   
1          16       0.001029                 0.000047       0.00407   
2          16       0.013350                 0.000056       0.00403   
3          16       0.021640                 0.000113       0.01130   
4          16       0.020900                 0.000095       0.00989   

   Jitter (ppq5)  Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  \
0        0.00615       0.01530          0.08510               0.0814   
1        0.00574       0.01220          0.04188               0.5570   
2        0.00663       0.01210          0.05257               0.7430   
3        0.01200       0.03389          0.06250               0.0781   
4        0.01107       0.02966          0.06128               0.8380   

   Shimmer (apq3)  Shimmer (apq5)  ...  Minimum pitch  Maximum pitch  \
0         0.03719         0.05185  ...         82.429        244.408   
1         0.01337         0.02081  ...        187.378        242.159   
2         0.01663         0.02859  ...        108.624        355.665   
3         0.01745         0.02950  ...        184.991        239.213   
4         0.02133         0.03216  ...        178.835        273.413   

   Number of pulses  Number of periods  Mean period  \
0                94                 93      0.00582   
1               113                112      0.00457   
2               122                120      0.00420   
3                69                 68      0.00524   
4                87                 86      0.00456   

   Standard deviation of period  Fraction of locally unvoiced frames  \
0                      0.001900                              0.00000   
1                      0.000297                              0.00641   
2                      0.000703                              0.02500   
3                      0.000254                              0.07759   
4                      0.000433                              0.01639   

   Number of voice breaks  Degree of voice breaks  status  
0                       0                     0.0       1  
1                       0                     0.0       1  
2                       0                     0.0       1  
3                       0                     0.0       1  
4                       0                     0.0       1  

[5 rows x 28 columns]

In [25]:
data_test.shape

(99, 28)

In [26]:
testing_X = data_test.iloc[:, 1:24].values
testing_X

array([[1.468e-02, 8.550e-05, 5.100e-03, ..., 9.300e+01, 5.820e-03,
        1.900e-03],
       [1.029e-03, 4.700e-05, 4.070e-03, ..., 1.120e+02, 4.570e-03,
        2.970e-04],
       [1.335e-02, 5.610e-05, 4.030e-03, ..., 1.200e+02, 4.200e-03,
        7.030e-04],
       ...,
       [6.290e-03, 6.700e-05, 3.600e-03, ..., 4.430e+02, 1.060e-02,
        1.460e-04],
       [3.880e-03, 4.110e-05, 2.000e-03, ..., 3.310e+02, 1.060e-02,
        1.600e-04],
       [8.550e-03, 7.950e-05, 4.150e-03, ..., 4.580e+02, 9.300e-03,
        2.520e-03]])

In [27]:
testing_X = standard_X.transform(testing_X)
testing_X

array([[ 0.95321144,  0.7537766 ,  0.20177657, ..., -0.93440741,
        -0.28617592,  3.94440071],
       [-1.02526328, -0.09952019, -0.04182414, ..., -0.87063961,
        -1.02932188, -0.20737227],
       [ 0.76045111,  0.10216815, -0.05128436, ..., -0.84379   ,
        -1.24929308,  0.84416848],
       ...,
       [-0.26277295,  0.34375087, -0.15298174, ...,  0.24026273,
         2.55561421, -0.59846255],
       [-0.61206048, -0.23028515, -0.5313906 , ..., -0.13563171,
         2.55561421, -0.56220252],
       [ 0.0647747 ,  0.62079528, -0.02290369, ...,  0.29060574,
         1.78274241,  5.55020186]])

In [28]:
y_predict_test = model.predict(testing_X)

In [29]:
y_predict_test

array([0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [30]:
total = 0
for i in y_predict_test:
    total = total + i
    
print(total)

39


In [31]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, random_state=12, test_size = 0.05)

In [32]:
min_max_scaler = preprocessing.MinMaxScaler()
X_train = min_max_scaler.fit_transform(X_train)
X_train

array([[0.0707193 , 0.10793975, 0.02949853, ..., 0.0760642 , 0.7123939 ,
        0.25491159],
       [0.13029789, 0.10045167, 0.10730088, ..., 0.07885555, 0.29714018,
        0.1547331 ],
       [0.06635989, 0.07381522, 0.03355457, ..., 0.17585485, 0.4522706 ,
        0.344246  ],
       ...,
       [0.14071204, 0.12889092, 0.11283186, ..., 0.17515701, 0.4113607 ,
        0.17086033],
       [0.1690482 , 0.27644731, 0.10693215, ..., 0.02930914, 0.99318377,
        0.32242896],
       [0.14579801, 0.17126328, 0.15117994, ..., 0.35101186, 0.61073174,
        0.02340506]])

In [33]:
X_test = min_max_scaler.transform(X_test)
X_test

array([[0.19738435, 0.18730825, 0.12389381, 0.14041268, 0.12400147,
        0.10883841, 0.19181034, 0.08921632, 0.06982366, 0.1369328 ,
        0.08924331, 0.91752493, 0.07960864, 0.7938975 , 0.24743588,
        0.2450266 , 0.04388076, 0.28907329, 0.1519222 , 0.06092437,
        0.06420098, 0.46416743, 0.12249198],
       [0.21821264, 0.16979207, 0.21865782, 0.23754404, 0.21875384,
        0.65937528, 0.67887931, 0.63293394, 0.59229238, 0.6076122 ,
        0.63293394, 0.66665167, 0.25876166, 0.27052624, 0.3515671 ,
        0.36402187, 0.07019252, 0.42545724, 0.37742743, 0.15616246,
        0.15910677, 0.33030563, 0.11078212],
       [0.02567208, 0.04454217, 0.01327434, 0.02617011, 0.0132727 ,
        0.08150679, 0.09967672, 0.05408031, 0.03891733, 0.10810811,
        0.05405332, 0.98908959, 0.00762495, 0.90239059, 0.20948112,
        0.2047659 , 0.01866097, 0.28986868, 0.12040859, 0.05882353,
        0.06210747, 0.52194262, 0.05709329],
       [0.15403245, 0.16346293, 0.06710914, 0.117

In [34]:
model_minmax = LogisticRegression()
model_minmax.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [35]:
y_pred = model_minmax.predict(X_test)

In [36]:
cm = confusion_matrix(Y_test, y_pred) # Calulate Confusion matrix for test set.
print(cm)

[[3 0]
 [2 1]]


In [39]:
testing_X = data_test.iloc[:, 1:24].values
testing_X

array([[1.468e-02, 8.550e-05, 5.100e-03, ..., 9.300e+01, 5.820e-03,
        1.900e-03],
       [1.029e-03, 4.700e-05, 4.070e-03, ..., 1.120e+02, 4.570e-03,
        2.970e-04],
       [1.335e-02, 5.610e-05, 4.030e-03, ..., 1.200e+02, 4.200e-03,
        7.030e-04],
       ...,
       [6.290e-03, 6.700e-05, 3.600e-03, ..., 4.430e+02, 1.060e-02,
        1.460e-04],
       [3.880e-03, 4.110e-05, 2.000e-03, ..., 3.310e+02, 1.060e-02,
        1.600e-04],
       [8.550e-03, 7.950e-05, 4.150e-03, ..., 4.580e+02, 9.300e-03,
        2.520e-03]])

In [40]:
testing_X = min_max_scaler.transform(testing_X)
testing_X

array([[ 0.30951804,  0.25434041,  0.16519174, ...,  0.02581996,
         0.38231429,  0.81985161],
       [-0.0210947 ,  0.13039755,  0.12721239, ...,  0.03907886,
         0.21563227,  0.1074021 ],
       [ 0.27730685,  0.15969314,  0.12573746, ...,  0.04466155,
         0.16629439,  0.28784782],
       ...,
       [ 0.10632114,  0.19478345,  0.10988201, ...,  0.27006281,
         1.01970635,  0.04029051],
       [ 0.0479535 ,  0.11140371,  0.05088496, ...,  0.19190509,
         1.01970635,  0.04651278],
       [ 0.16105595,  0.23502464,  0.13016224, ...,  0.28053036,
         0.84635704,  1.09540912]])

In [41]:
y_test_predict = model_minmax.predict(testing_X)

In [42]:
y_test_predict

array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0], dtype=int64)

In [43]:
total = 0
for i in y_predict_test:
    total = total + i
    
print(total)

39
