In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score

In [2]:
data = pd.read_csv(r'..\Datasets\Parkinsons Processed Training - Only Vowels.csv', header = 0)
data.head()

Subject Id  Jitter(local)  Jitter(local, absolute)  Jitter (rap)  \
0           1        0.01488                 0.000090       0.00900   
1           1        0.00728                 0.000038       0.00353   
2           1        0.01220                 0.000074       0.00732   
3           2        0.00427                 0.000034       0.00243   
4           2        0.00844                 0.000069       0.00509   

   Jitter (ppq5)  Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  \
0        0.00794       0.02699          0.08334                0.779   
1        0.00376       0.01059          0.05864                0.642   
2        0.00670       0.02196          0.08719                0.875   
3        0.00249       0.00728          0.07428                0.694   
4        0.00489       0.01527          0.14053                1.239   

   Shimmer (apq3)  Shimmer (apq5)  ...  Maximum pitch  Number of pulses  \
0         0.04517         0.04609  ...        187.576               160   
1         0.02058         0.03180  ...        234.505               170   
2         0.04347         0.05166  ...        211.442              1431   
3         0.04205         0.04311  ...        129.205               345   
4         0.06131         0.07015  ...        126.788               585   

   Number of periods  Mean period  Standard deviation of period  \
0                159     0.006065                      0.000416   
1                169     0.005181                      0.000403   
2               1427     0.006071                      0.000474   
3                344     0.008073                      0.000143   
4                582     0.008174                      0.000123   

   Fraction of locally unvoiced frames  Number of voice breaks  \
0                              0.00000                       0   
1                              0.02247                       0   
2                              0.10656                       1   
3                              0.00000                       0   
4                              0.00209                       2   

   Degree of voice breaks  UPDRS  status  
0                 0.00000     23       1  
1                 0.00000     23       1  
2                 0.00178     23       1  
3                 0.00000      8       1  
4                 0.00768      8       1  

[5 rows x 29 columns]

In [3]:
data.shape

(120, 29)

In [4]:
X_table = data.iloc[:, 1:27]

In [5]:
X_table

Jitter(local)  Jitter(local, absolute)  Jitter (rap)  Jitter (ppq5)  \
0          0.01488                 0.000090       0.00900        0.00794   
1          0.00728                 0.000038       0.00353        0.00376   
2          0.01220                 0.000074       0.00732        0.00670   
3          0.00427                 0.000034       0.00243        0.00249   
4          0.00844                 0.000069       0.00509        0.00489   
..             ...                      ...           ...            ...   
115        0.00601                 0.000031       0.00316        0.00339   
116        0.00382                 0.000017       0.00169        0.00203   
117        0.00471                 0.000034       0.00186        0.00230   
118        0.04319                 0.000317       0.02774        0.01708   
119        0.01543                 0.000103       0.01004        0.00648   

     Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  Shimmer (apq3)  \
0         0.02699          0.08334                0.779         0.04517   
1         0.01059          0.05864                0.642         0.02058   
2         0.02196          0.08719                0.875         0.04347   
3         0.00728          0.07428                0.694         0.04205   
4         0.01527          0.14053                1.239         0.06131   
..            ...              ...                  ...             ...   
115       0.00947          0.07492                0.681         0.03729   
116       0.00508          0.06905                0.648         0.02728   
117       0.00558          0.02793                0.260         0.01183   
118       0.08322          0.13924                1.195         0.08558   
119       0.03012          0.17447                1.694         0.11171   

     Shimmer (apq5)  Shimmer (apq11)  ...  Standard deviation  Minimum pitch  \
0           0.04609          0.06802  ...              10.421        142.229   
1           0.03180          0.07194  ...              14.773        159.515   
2           0.05166          0.07548  ...              12.981        146.445   
3           0.04311          0.05250  ...               2.179        118.461   
4           0.07015          0.09260  ...               1.650        118.020   
..              ...              ...  ...                 ...            ...   
115         0.04581          0.06352  ...              28.380         99.593   
116         0.03968          0.06920  ...               6.486        205.108   
117         0.01520          0.02576  ...               2.273        132.744   
118         0.06036          0.08585  ...               4.846        124.543   
119         0.06851          0.09395  ...               1.886        141.443   

     Maximum pitch  Number of pulses  Number of periods  Mean period  \
0          187.576               160                159     0.006065   
1          234.505               170                169     0.005181   
2          211.442              1431               1427     0.006071   
3          129.205               345                344     0.008073   
4          126.788               585                582     0.008174   
..             ...               ...                ...          ...   
115        214.486               215                213     0.005161   
116        237.431               188                187     0.004490   
117        145.840               176                175     0.007179   
118        165.029               258                256     0.007343   
119        158.612               426                425     0.006700   

     Standard deviation of period  Fraction of locally unvoiced frames  \
0                        0.000416                              0.00000   
1                        0.000403                              0.02247   
2                        0.000474                              0.10656   
3                        0.000143                              0.0000

In [6]:
X = data.iloc[:, 1:27].values
X

array([[1.48800e-02, 9.02130e-05, 9.00000e-03, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [7.28000e-03, 3.76980e-05, 3.53000e-03, ..., 2.24700e-02,
        0.00000e+00, 0.00000e+00],
       [1.22000e-02, 7.40410e-05, 7.32000e-03, ..., 1.06560e-01,
        1.00000e+00, 1.78000e-03],
       ...,
       [4.71000e-03, 3.38370e-05, 1.86000e-03, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [4.31900e-02, 3.17122e-04, 2.77400e-02, ..., 2.91300e-02,
        1.00000e+00, 7.03800e-02],
       [1.54300e-02, 1.03357e-04, 1.00400e-02, ..., 3.51000e-03,
        0.00000e+00, 0.00000e+00]])

In [7]:
y = data.iloc[:, -1].values

In [8]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [9]:
y.size

120

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, random_state=12, test_size = 0.2)

In [11]:
standard_X = StandardScaler()
X_train = standard_X.fit_transform(X_train)
X_test = standard_X.transform(X_test)

In [12]:
X_train

array([[-0.77362312, -0.87707013, -0.69142507, ...,  0.0433652 ,
        -0.3881606 , -0.28857239],
       [-0.70283741, -0.6114199 , -0.64476377, ..., -0.47428312,
         1.52278387, -0.07922324],
       [-0.34074129, -0.6188083 , -0.2181462 , ..., -0.51156573,
        -0.3881606 , -0.28857239],
       ...,
       [ 0.86533825,  0.19304371,  1.01504524, ..., -0.51156573,
        -0.3881606 , -0.28857239],
       [ 0.04177378,  0.78662669, -0.22925603, ...,  0.39233042,
        -0.3881606 , -0.28857239],
       [-0.08890753,  0.10853373,  0.03737996, ...,  0.02546955,
         0.56731164,  0.20706437]])

In [13]:
X_test

array([[ 2.01041617e-01,  2.11971285e-01, -1.27045567e-01,
        -2.24578254e-01, -1.26994786e-01, -7.65344093e-01,
        -5.70735752e-01, -7.83831669e-01, -6.70727011e-01,
        -6.88141085e-01, -7.83731314e-01,  3.57681154e-01,
        -2.54615427e-01,  1.06934844e+00, -3.06098069e-01,
        -3.54577404e-01, -2.20752541e-01, -2.70209142e-01,
        -4.60817422e-01, -7.21986126e-01, -7.16399337e-01,
         8.61475292e-02, -9.63419814e-02, -5.11565733e-01,
        -3.88160595e-01, -2.88572388e-01],
       [ 3.18110286e-01,  9.90491840e-02,  4.43999837e-01,
         2.69072937e-01,  4.43995743e-01,  1.54869669e+00,
         1.41916949e+00,  1.47959576e+00,  2.17226370e+00,
         1.25596003e+00,  1.47957107e+00, -8.18127680e-01,
         6.12100507e-01, -1.29025058e+00,  2.08395114e-01,
         2.23794398e-01, -2.92128969e-02,  3.96870872e-01,
         5.46069591e-01, -2.98105792e-01, -2.92443678e-01,
        -4.92874386e-01, -1.63959612e-01, -5.11565733e-01,
        -3.88

In [14]:
model = LogisticRegression(C = 50, solver = 'sag')

In [15]:
model.fit(X_train, Y_train)

C:\Anaconda\lib\site-packages\sklearn\linear_model\_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


LogisticRegression(C=50, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='sag', tol=0.0001, verbose=0,
                   warm_start=False)

In [16]:
y_pred = model.predict(X_test)

In [17]:
cm = confusion_matrix(Y_test, y_pred) # Calulate Confusion matrix for test set.
print(cm)

[[ 6  3]
 [ 2 13]]


In [18]:
print(accuracy_score(Y_test, y_pred))

0.7916666666666666


In [34]:
data_test = pd.read_csv(r'../Datasets/Sri Lankan Dataset.csv', header = 0)
data_test.head()

Subject ID  Jitter(local)  Jitter(local, absolute)  Jitter (rap)  \
0          17        0.01119                 0.000085       0.00387   
1          17        0.01001                 0.000071       0.00314   
2          17        0.00576                 0.000043       0.00221   
3          17        0.01288                 0.000104       0.00559   
4          17        0.00784                 0.000060       0.00243   

   Jitter (ppq5)  Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  \
0        0.00433       0.01160          0.04168                0.490   
1        0.00416       0.00943          0.03785                0.493   
2        0.00289       0.00663          0.03913                0.439   
3        0.00603       0.01677          0.04783                0.502   
4        0.00314       0.00729          0.03155                0.431   

   Shimmer (apq3)  Shimmer (apq5)  ...  Standard deviation  Minimum pitch  \
0         0.01733         0.02246  ...              34.427         96.944   
1         0.01256         0.02010  ...              39.380        104.679   
2         0.01367         0.01944  ...               4.531        123.548   
3         0.02122         0.02702  ...               3.448        107.007   
4         0.01156         0.01636  ...              18.480        109.714   

   Maximum pitch  Number of pulses  Number of periods  Mean period  \
0        254.919               142                141      0.00762   
1        247.911               180                178      0.00710   
2        142.684               139                138      0.00753   
3        133.246               120                119      0.00804   
4        252.798               162                161      0.00769   

   Standard deviation of period  Fraction of locally unvoiced frames  \
0                      0.001520                              0.73839   
1                      0.001670                              0.62000   
2                      0.000260                              0.67122   
3                      0.000270                              0.67381   
4                      0.000826                              0.56169   

   Number of voice breaks  Degree of voice breaks  
0                       0                 0.00000  
1                       1                 0.06049  
2                       0                 0.00000  
3                       0                 0.00000  
4                       0                 0.00000  

[5 rows x 27 columns]

In [20]:
testing_X = data_test.iloc[:, 1:].values
testing_X

array([[1.1190e-02, 8.5200e-05, 3.8700e-03, ..., 7.3839e-01, 0.0000e+00,
        0.0000e+00],
       [1.0010e-02, 7.1100e-05, 3.1400e-03, ..., 6.2000e-01, 1.0000e+00,
        6.0490e-02],
       [5.7600e-03, 4.3300e-05, 2.2100e-03, ..., 6.7122e-01, 0.0000e+00,
        0.0000e+00],
       ...,
       [4.6700e-03, 2.4506e-05, 2.4300e-03, ..., 6.6244e-01, 0.0000e+00,
        0.0000e+00],
       [4.6800e-03, 2.4112e-05, 1.8400e-03, ..., 7.2462e-01, 1.0000e+00,
        1.1000e-02],
       [3.9600e-03, 1.7697e-05, 1.4600e-03, ..., 7.1154e-01, 0.0000e+00,
        0.0000e+00]])

In [21]:
testing_X = standard_X.transform(testing_X)
testing_X

array([[ 0.35622567,  0.63788332, -0.1514872 , ..., 11.72359253,
        -0.3881606 , -0.28857239],
       [ 0.19559656,  0.34525299, -0.31369076, ...,  9.76186447,
         0.56731164,  0.99706516],
       [-0.38294047, -0.23170611, -0.52033365, ..., 10.61058236,
        -0.3881606 , -0.28857239],
       ...,
       [-0.5313182 , -0.62175536, -0.47145038, ..., 10.46509733,
        -0.3881606 , -0.28857239],
       [-0.52995693, -0.6299324 , -0.60254641, ..., 11.49542296,
         0.56731164, -0.05478146],
       [-0.62796791, -0.76306883, -0.68698114, ..., 11.27868673,
        -0.3881606 , -0.28857239]])

In [22]:
y_predict_test = model.predict(testing_X)

In [23]:
y_predict_test

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [24]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, random_state=12, test_size = 0.2)

In [25]:
min_max_scaler = preprocessing.MinMaxScaler()
X_train = min_max_scaler.fit_transform(X_train)
X_train

array([[0.02397675, 0.01837896, 0.03023599, ..., 0.09568571, 0.        ,
        0.        ],
       [0.0365706 , 0.05958593, 0.03797935, ..., 0.00642857, 0.33333333,
        0.03733606],
       [0.10099298, 0.05843987, 0.10877581, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.31557278, 0.18437225, 0.31342183, ..., 0.        , 0.        ,
        0.        ],
       [0.1690482 , 0.27644731, 0.10693215, ..., 0.15585714, 0.        ,
        0.        ],
       [0.14579801, 0.17126328, 0.15117994, ..., 0.0926    , 0.16666667,
        0.0883936 ]])

In [26]:
X_test = min_max_scaler.transform(X_test)
X_test

array([[ 0.19738435,  0.18730825,  0.12389381,  0.14041268,  0.12400147,
         0.10883841,  0.19181034,  0.08921632,  0.06982366,  0.1369328 ,
         0.08924331,  0.91752493,  0.07960864,  0.7938975 ,  0.24743588,
         0.2450266 ,  0.04388076,  0.2643565 ,  0.15074201,  0.06092437,
         0.06420098,  0.46416743,  0.12249198,  0.        ,  0.        ,
         0.        ],
       [ 0.21821264,  0.16979207,  0.21865782,  0.23754404,  0.21875384,
         0.65937528,  0.67887931,  0.63293394,  0.59229238,  0.6076122 ,
         0.63293394,  0.66665167,  0.25876166,  0.27052624,  0.3515671 ,
         0.36402187,  0.07019252,  0.40548211,  0.37656106,  0.15616246,
         0.15910677,  0.33030563,  0.11078212,  0.        ,  0.        ,
         0.        ],
       [ 0.02567208,  0.04454217,  0.01327434,  0.02617011,  0.0132727 ,
         0.08150679,  0.09967672,  0.05408031,  0.03891733,  0.10810811,
         0.05405332,  0.98908959,  0.00762495,  0.90239059,  0.20948112,
       

In [27]:
model_minmax = LogisticRegression(C = 50, solver = 'sag')
model_minmax.fit(X_train, Y_train)

C:\Anaconda\lib\site-packages\sklearn\linear_model\_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


LogisticRegression(C=50, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='sag', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
y_pred = model_minmax.predict(X_test)

In [29]:
cm = confusion_matrix(Y_test, y_pred) # Calulate Confusion matrix for test set.
print(cm)

[[ 6  3]
 [ 3 12]]


In [30]:
testing_X = data_test.iloc[:, 1:].values
testing_X

array([[1.1190e-02, 8.5200e-05, 3.8700e-03, ..., 7.3839e-01, 0.0000e+00,
        0.0000e+00],
       [1.0010e-02, 7.1100e-05, 3.1400e-03, ..., 6.2000e-01, 1.0000e+00,
        6.0490e-02],
       [5.7600e-03, 4.3300e-05, 2.2100e-03, ..., 6.7122e-01, 0.0000e+00,
        0.0000e+00],
       ...,
       [4.6700e-03, 2.4506e-05, 2.4300e-03, ..., 6.6244e-01, 0.0000e+00,
        0.0000e+00],
       [4.6800e-03, 2.4112e-05, 1.8400e-03, ..., 7.2462e-01, 1.0000e+00,
        1.1000e-02],
       [3.9600e-03, 1.7697e-05, 1.4600e-03, ..., 7.1154e-01, 0.0000e+00,
        0.0000e+00]])

In [31]:
testing_X = min_max_scaler.transform(testing_X)
testing_X

array([[0.22499395, 0.25337463, 0.11983776, ..., 2.10968571, 0.        ,
        0.        ],
       [0.1964156 , 0.20798256, 0.09292035, ..., 1.77142857, 0.16666667,
        0.22928512],
       [0.09348511, 0.11848616, 0.05862832, ..., 1.91777143, 0.        ,
        0.        ],
       ...,
       [0.06708646, 0.05798273, 0.06674041, ..., 1.89268571, 0.        ,
        0.        ],
       [0.06732865, 0.05671432, 0.04498525, ..., 2.07034286, 0.16666667,
        0.0416951 ],
       [0.04989101, 0.03606254, 0.03097345, ..., 2.03297143, 0.        ,
        0.        ]])

In [32]:
y_test_predict = model_minmax.predict(testing_X)

In [33]:
y_test_predict

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64)