In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
import tensorflow as tf

In [2]:
tf.__version__

'2.1.0'

In [3]:
data = pd.read_csv(r'..\Datasets\Parkinsons Processed Training - Only Vowels.csv', header = 0)
data.head()

Subject Id  Jitter(local)  Jitter(local, absolute)  Jitter (rap)  \
0           1        0.01488                 0.000090       0.00900   
1           1        0.00728                 0.000038       0.00353   
2           1        0.01220                 0.000074       0.00732   
3           2        0.00427                 0.000034       0.00243   
4           2        0.00844                 0.000069       0.00509   

   Jitter (ppq5)  Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  \
0        0.00794       0.02699          0.08334                0.779   
1        0.00376       0.01059          0.05864                0.642   
2        0.00670       0.02196          0.08719                0.875   
3        0.00249       0.00728          0.07428                0.694   
4        0.00489       0.01527          0.14053                1.239   

   Shimmer (apq3)  Shimmer (apq5)  ...  Maximum pitch  Number of pulses  \
0         0.04517         0.04609  ...        187.576               160   
1         0.02058         0.03180  ...        234.505               170   
2         0.04347         0.05166  ...        211.442              1431   
3         0.04205         0.04311  ...        129.205               345   
4         0.06131         0.07015  ...        126.788               585   

   Number of periods  Mean period  Standard deviation of period  \
0                159     0.006065                      0.000416   
1                169     0.005181                      0.000403   
2               1427     0.006071                      0.000474   
3                344     0.008073                      0.000143   
4                582     0.008174                      0.000123   

   Fraction of locally unvoiced frames  Number of voice breaks  \
0                              0.00000                       0   
1                              0.02247                       0   
2                              0.10656                       1   
3                              0.00000                       0   
4                              0.00209                       2   

   Degree of voice breaks  UPDRS  status  
0                 0.00000     23       1  
1                 0.00000     23       1  
2                 0.00178     23       1  
3                 0.00000      8       1  
4                 0.00768      8       1  

[5 rows x 29 columns]

In [4]:
X = data.iloc[:, 1:24].values
X

array([[1.488000e-02, 9.021300e-05, 9.000000e-03, ..., 1.590000e+02,
        6.064725e-03, 4.162760e-04],
       [7.280000e-03, 3.769800e-05, 3.530000e-03, ..., 1.690000e+02,
        5.181253e-03, 4.034940e-04],
       [1.220000e-02, 7.404100e-05, 7.320000e-03, ..., 1.427000e+03,
        6.070749e-03, 4.742890e-04],
       ...,
       [4.710000e-03, 3.383700e-05, 1.860000e-03, ..., 1.750000e+02,
        7.178780e-03, 1.298030e-04],
       [4.319000e-02, 3.171220e-04, 2.774000e-02, ..., 2.560000e+02,
        7.342534e-03, 3.119150e-04],
       [1.543000e-02, 1.033570e-04, 1.004000e-02, ..., 4.250000e+02,
        6.700038e-03, 1.082910e-04]])

In [5]:
y = data.iloc[:, -1].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [6]:
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)
X_scale

array([[0.31436183, 0.26951295, 0.30899705, ..., 0.07187718, 0.4149473 ,
        0.16041403],
       [0.13029789, 0.10045167, 0.10730088, ..., 0.07885555, 0.29714018,
        0.1547331 ],
       [0.24945507, 0.21745051, 0.24705015, ..., 0.95673412, 0.41575057,
        0.18619777],
       ...,
       [0.06805522, 0.08802197, 0.04572271, ..., 0.08304257, 0.56350165,
        0.03309179],
       [1.        , 1.        , 1.        , ..., 0.13956734, 0.58533753,
        0.11403103],
       [0.32768225, 0.31182737, 0.34734513, ..., 0.25750174, 0.4996635 ,
        0.02353083]])

In [26]:
model = tf.keras.models.Sequential()

In [27]:
model.add(tf.keras.layers.Dense(units=23, activation='sigmoid'))

In [28]:
model.add(tf.keras.layers.Dense(units=50, activation='relu'))

In [29]:
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [30]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [31]:
model.fit(X_scale, y, batch_size = 120, epochs = 500)

Train on 120 samples
Epoch 1/500
120/120 [==============================] - 0s 3ms/sample - loss: 0.7172 - accuracy: 0.5000
Epoch 2/500
120/120 [==============================] - 0s 25us/sample - loss: 0.7097 - accuracy: 0.5000
Epoch 3/500
120/120 [==============================] - 0s 25us/sample - loss: 0.7036 - accuracy: 0.5000
Epoch 4/500
120/120 [==============================] - 0s 25us/sample - loss: 0.6991 - accuracy: 0.5000
Epoch 5/500
120/120 [==============================] - 0s 33us/sample - loss: 0.6959 - accuracy: 0.5000
Epoch 6/500
120/120 [==============================] - 0s 33us/sample - loss: 0.6940 - accuracy: 0.5000
Epoch 7/500
120/120 [==============================] - 0s 33us/sample - loss: 0.6931 - accuracy: 0.5167
Epoch 8/500
120/120 [==============================] - 0s 25us/sample - loss: 0.6931 - accuracy: 0.5083
Epoch 9/500
120/120 [==============================] - 0s 34us/sample - loss: 0.6935 - accuracy: 0.5000
Epoch 10/500
120/120 [======================

Epoch 79/500
120/120 [==============================] - 0s 50us/sample - loss: 0.6800 - accuracy: 0.6083
Epoch 80/500
120/120 [==============================] - 0s 42us/sample - loss: 0.6797 - accuracy: 0.6083
Epoch 81/500
120/120 [==============================] - 0s 42us/sample - loss: 0.6794 - accuracy: 0.5917
Epoch 82/500
120/120 [==============================] - 0s 42us/sample - loss: 0.6791 - accuracy: 0.6000
Epoch 83/500
120/120 [==============================] - 0s 58us/sample - loss: 0.6788 - accuracy: 0.6000
Epoch 84/500
120/120 [==============================] - 0s 42us/sample - loss: 0.6785 - accuracy: 0.6000
Epoch 85/500
120/120 [==============================] - 0s 33us/sample - loss: 0.6782 - accuracy: 0.5917
Epoch 86/500
120/120 [==============================] - 0s 34us/sample - loss: 0.6779 - accuracy: 0.5917
Epoch 87/500
120/120 [==============================] - 0s 25us/sample - loss: 0.6776 - accuracy: 0.6083
Epoch 88/500
120/120 [==============================] -

Epoch 157/500
120/120 [==============================] - 0s 25us/sample - loss: 0.6405 - accuracy: 0.6083
Epoch 158/500
120/120 [==============================] - 0s 33us/sample - loss: 0.6398 - accuracy: 0.6083
Epoch 159/500
120/120 [==============================] - 0s 25us/sample - loss: 0.6390 - accuracy: 0.6083
Epoch 160/500
120/120 [==============================] - 0s 25us/sample - loss: 0.6382 - accuracy: 0.6000
Epoch 161/500
120/120 [==============================] - 0s 42us/sample - loss: 0.6374 - accuracy: 0.6083
Epoch 162/500
120/120 [==============================] - 0s 33us/sample - loss: 0.6367 - accuracy: 0.6000
Epoch 163/500
120/120 [==============================] - 0s 33us/sample - loss: 0.6359 - accuracy: 0.6083
Epoch 164/500
120/120 [==============================] - 0s 33us/sample - loss: 0.6351 - accuracy: 0.6000
Epoch 165/500
120/120 [==============================] - 0s 25us/sample - loss: 0.6343 - accuracy: 0.6000
Epoch 166/500
120/120 [=======================

Epoch 235/500
120/120 [==============================] - 0s 33us/sample - loss: 0.5742 - accuracy: 0.6750
Epoch 236/500
120/120 [==============================] - 0s 42us/sample - loss: 0.5733 - accuracy: 0.6750
Epoch 237/500
120/120 [==============================] - 0s 25us/sample - loss: 0.5725 - accuracy: 0.6750
Epoch 238/500
120/120 [==============================] - 0s 42us/sample - loss: 0.5716 - accuracy: 0.6750
Epoch 239/500
120/120 [==============================] - 0s 33us/sample - loss: 0.5708 - accuracy: 0.6750
Epoch 240/500
120/120 [==============================] - 0s 42us/sample - loss: 0.5700 - accuracy: 0.6750
Epoch 241/500
120/120 [==============================] - 0s 42us/sample - loss: 0.5691 - accuracy: 0.6833
Epoch 242/500
120/120 [==============================] - 0s 33us/sample - loss: 0.5683 - accuracy: 0.6833
Epoch 243/500
120/120 [==============================] - 0s 33us/sample - loss: 0.5674 - accuracy: 0.6833
Epoch 244/500
120/120 [=======================

Epoch 313/500
120/120 [==============================] - 0s 33us/sample - loss: 0.5191 - accuracy: 0.7167
Epoch 314/500
120/120 [==============================] - 0s 25us/sample - loss: 0.5186 - accuracy: 0.7167
Epoch 315/500
120/120 [==============================] - 0s 25us/sample - loss: 0.5181 - accuracy: 0.7167
Epoch 316/500
120/120 [==============================] - 0s 33us/sample - loss: 0.5177 - accuracy: 0.7167
Epoch 317/500
120/120 [==============================] - 0s 25us/sample - loss: 0.5172 - accuracy: 0.7167
Epoch 318/500
120/120 [==============================] - 0s 33us/sample - loss: 0.5167 - accuracy: 0.7167
Epoch 319/500
120/120 [==============================] - 0s 33us/sample - loss: 0.5162 - accuracy: 0.7167
Epoch 320/500
120/120 [==============================] - 0s 25us/sample - loss: 0.5158 - accuracy: 0.7167
Epoch 321/500
120/120 [==============================] - 0s 42us/sample - loss: 0.5153 - accuracy: 0.7167
Epoch 322/500
120/120 [=======================

Epoch 391/500
120/120 [==============================] - 0s 25us/sample - loss: 0.4943 - accuracy: 0.7417
Epoch 392/500
120/120 [==============================] - 0s 25us/sample - loss: 0.4941 - accuracy: 0.7417
Epoch 393/500
120/120 [==============================] - 0s 33us/sample - loss: 0.4939 - accuracy: 0.7417
Epoch 394/500
120/120 [==============================] - 0s 33us/sample - loss: 0.4938 - accuracy: 0.7417
Epoch 395/500
120/120 [==============================] - 0s 42us/sample - loss: 0.4936 - accuracy: 0.7417
Epoch 396/500
120/120 [==============================] - 0s 17us/sample - loss: 0.4934 - accuracy: 0.7417
Epoch 397/500
120/120 [==============================] - 0s 33us/sample - loss: 0.4932 - accuracy: 0.7417
Epoch 398/500
120/120 [==============================] - 0s 42us/sample - loss: 0.4930 - accuracy: 0.7417
Epoch 399/500
120/120 [==============================] - 0s 33us/sample - loss: 0.4929 - accuracy: 0.7417
Epoch 400/500
120/120 [=======================

Epoch 469/500
120/120 [==============================] - 0s 25us/sample - loss: 0.4832 - accuracy: 0.7417
Epoch 470/500
120/120 [==============================] - 0s 25us/sample - loss: 0.4831 - accuracy: 0.7417
Epoch 471/500
120/120 [==============================] - 0s 25us/sample - loss: 0.4829 - accuracy: 0.7417
Epoch 472/500
120/120 [==============================] - 0s 16us/sample - loss: 0.4828 - accuracy: 0.7417
Epoch 473/500
120/120 [==============================] - 0s 18us/sample - loss: 0.4827 - accuracy: 0.7417
Epoch 474/500
120/120 [==============================] - 0s 0s/sample - loss: 0.4826 - accuracy: 0.7417
Epoch 475/500
120/120 [==============================] - 0s 0s/sample - loss: 0.4825 - accuracy: 0.7417
Epoch 476/500
120/120 [==============================] - 0s 0s/sample - loss: 0.4823 - accuracy: 0.7417
Epoch 477/500
120/120 [==============================] - 0s 130us/sample - loss: 0.4822 - accuracy: 0.7417
Epoch 478/500
120/120 [============================

In [32]:
y_pred = model.predict(X)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y.reshape(len(y),1)),1))

[[0 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [33]:
data_test = pd.read_csv(r'../Datasets/Sri Lankan Dataset.csv', header = 0)
data_test.head()

Subject ID  Jitter(local)  Jitter(local, absolute)  Jitter (rap)  \
0          17        0.01119                 0.000085       0.00387   
1          17        0.01001                 0.000071       0.00314   
2          17        0.00576                 0.000043       0.00221   
3          17        0.01288                 0.000104       0.00559   
4          17        0.00784                 0.000060       0.00243   

   Jitter (ppq5)  Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  \
0        0.00433       0.01160          0.04168                0.490   
1        0.00416       0.00943          0.03785                0.493   
2        0.00289       0.00663          0.03913                0.439   
3        0.00603       0.01677          0.04783                0.502   
4        0.00314       0.00729          0.03155                0.431   

   Shimmer (apq3)  Shimmer (apq5)  ...  Standard deviation  Minimum pitch  \
0         0.01733         0.02246  ...              34.427         96.944   
1         0.01256         0.02010  ...              39.380        104.679   
2         0.01367         0.01944  ...               4.531        123.548   
3         0.02122         0.02702  ...               3.448        107.007   
4         0.01156         0.01636  ...              18.480        109.714   

   Maximum pitch  Number of pulses  Number of periods  Mean period  \
0        254.919               142                141      0.00762   
1        247.911               180                178      0.00710   
2        142.684               139                138      0.00753   
3        133.246               120                119      0.00804   
4        252.798               162                161      0.00769   

   Standard deviation of period  Fraction of locally unvoiced frames  \
0                      0.001520                              0.73839   
1                      0.001670                              0.62000   
2                      0.000260                              0.67122   
3                      0.000270                              0.67381   
4                      0.000826                              0.56169   

   Number of voice breaks  Degree of voice breaks  
0                       0                 0.00000  
1                       1                 0.06049  
2                       0                 0.00000  
3                       0                 0.00000  
4                       0                 0.00000  

[5 rows x 27 columns]

In [34]:
testing_X = data_test.iloc[:, 1:24].values
testing_X

array([[1.119000e-02, 8.520000e-05, 3.870000e-03, ..., 1.410000e+02,
        7.620000e-03, 1.520000e-03],
       [1.001000e-02, 7.110000e-05, 3.140000e-03, ..., 1.780000e+02,
        7.100000e-03, 1.670000e-03],
       [5.760000e-03, 4.330000e-05, 2.210000e-03, ..., 1.380000e+02,
        7.530000e-03, 2.600000e-04],
       ...,
       [4.670000e-03, 2.450600e-05, 2.430000e-03, ..., 1.640000e+02,
        5.249619e-03, 1.654250e-04],
       [4.680000e-03, 2.411200e-05, 1.840000e-03, ..., 1.350000e+02,
        5.155909e-03, 4.772440e-04],
       [3.960000e-03, 1.769700e-05, 1.460000e-03, ..., 1.650000e+02,
        4.471620e-03, 1.680530e-04]])

In [35]:
testing_X = min_max_scaler.transform(testing_X)
testing_X

array([[0.22499395, 0.25337463, 0.11983776, ..., 0.05931612, 0.6223364 ,
        0.65096152],
       [0.1964156 , 0.20798256, 0.09292035, ..., 0.08513608, 0.55299668,
        0.71762866],
       [0.09348511, 0.11848616, 0.05862832, ..., 0.05722261, 0.6103353 ,
        0.09095754],
       ...,
       [0.06708646, 0.05798273, 0.06674041, ..., 0.07536636, 0.30625648,
        0.0489239 ],
       [0.06732865, 0.05671432, 0.04498525, ..., 0.0551291 , 0.29376067,
        0.18751111],
       [0.04989101, 0.03606254, 0.03097345, ..., 0.0760642 , 0.20251372,
        0.05009191]])

In [36]:
pred_y_testing = model.predict(testing_X)

In [37]:
pred_y_testing = (pred_y_testing > 0.5)

In [38]:
pred_y_testing

array([[False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False]])

In [39]:
pred_array = []
for i in pred_y_testing:
    for j in i:
        if j == False:
            pred_array.append(0)
        else:
            pred_array.append(1)

In [40]:
pred_array

[0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0]

In [41]:
total = 0
for i in pred_array:
    total = total + i

print(total)

23


In [42]:
len(pred_array)

60

In [43]:
import os
os.environ["PATH"] += os.pathsep + 'C:/Program Files (x86)/Graphviz2.38/bin/'

In [44]:
from keras.utils import plot_model
plot_model(model, to_file='model.png')

OSError: `pydot` failed to call GraphViz.Please install GraphViz (https://www.graphviz.org/) and ensure that its executables are in the $PATH.