In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from xgboost import XGBClassifier

In [84]:
data = pd.read_csv(r'..\Datasets\Parkinsons Processed Training - Only Vowels - Sri Lankan.csv', header = 0)
data.head()

Subject Id  Jitter(local)  Jitter(local, absolute)  Jitter (rap)  \
0           1        0.01488                 0.000090       0.00900   
1           1        0.00728                 0.000038       0.00353   
2           1        0.00472                 0.000031       0.00224   
3           2        0.00427                 0.000034       0.00243   
4           2        0.00844                 0.000069       0.00509   

   Jitter (ppq5)  Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  \
0        0.00794       0.02699          0.08334                0.779   
1        0.00376       0.01059          0.05864                0.642   
2        0.00245       0.00673          0.06404                0.629   
3        0.00249       0.00728          0.07428                0.694   
4        0.00489       0.01527          0.14053                1.239   

   Shimmer (apq3)  Shimmer (apq5)  ...  Maximum pitch  Number of pulses  \
0         0.04517         0.04609  ...        187.576               160   
1         0.02058         0.03180  ...        234.505               170   
2         0.03434         0.03765  ...        190.019               675   
3         0.04205         0.04311  ...        129.205               345   
4         0.06131         0.07015  ...        126.788               585   

   Number of periods  Mean period  Standard deviation of period  \
0                159     0.006065                      0.000416   
1                169     0.005181                      0.000403   
2                673     0.006649                      0.000132   
3                344     0.008073                      0.000143   
4                582     0.008174                      0.000123   

   Fraction of locally unvoiced frames  Number of voice breaks  \
0                              0.00000                       0   
1                              0.02247                       0   
2                              0.26180                       1   
3                              0.00000                       0   
4                              0.00209                       2   

   Degree of voice breaks  UPDRS  status  
0                 0.00000     23       1  
1                 0.00000     23       1  
2                 0.26325     23       1  
3                 0.00000      8       1  
4                 0.00768      8       1  

[5 rows x 29 columns]

In [85]:
X = data.iloc[:, 1:24].values
X

array([[1.488000e-02, 9.021300e-05, 9.000000e-03, ..., 1.590000e+02,
        6.064725e-03, 4.162760e-04],
       [7.280000e-03, 3.769800e-05, 3.530000e-03, ..., 1.690000e+02,
        5.181253e-03, 4.034940e-04],
       [4.720000e-03, 3.137300e-05, 2.240000e-03, ..., 6.730000e+02,
        6.649119e-03, 1.321080e-04],
       ...,
       [4.710000e-03, 3.383700e-05, 1.860000e-03, ..., 1.750000e+02,
        7.178780e-03, 1.298030e-04],
       [4.319000e-02, 3.171220e-04, 2.774000e-02, ..., 2.560000e+02,
        7.342534e-03, 3.119150e-04],
       [1.543000e-02, 1.033570e-04, 1.004000e-02, ..., 4.250000e+02,
        6.700038e-03, 1.082910e-04]])

In [86]:
y = data.iloc[:, -1].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [489]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, random_state=12, test_size = 0.01)

In [490]:
standard_X = StandardScaler()
X_train = standard_X.fit_transform(X_train)
X_test = standard_X.transform(X_test)

In [491]:
model = XGBClassifier(max_depth = 2, learning_rate=0.015, n_estimators = 600)
model.fit(X_train, Y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.015, max_delta_step=0, max_depth=2,
              min_child_weight=1, missing=None, n_estimators=600, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [492]:
y_pred = model.predict(X_test)

In [493]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred) # Calulate Confusion matrix for test set.
print(cm)

[[0 1]
 [0 1]]


In [494]:
# Evaluate
print("Accuracy for training set -> ", end = "")
scale_X = standard_X.transform(X)
Y_hat = [round(yhat) for yhat in model.predict(scale_X)]
print(accuracy_score(y, Y_hat)) # Full set accuracy
Y_hat = [round(yhat) for yhat in model.predict(X_test)]
print("Accuracy for test set -> ", end = "")
print(accuracy_score(Y_test, Y_hat)) # Test set accuracy

Accuracy for training set -> 0.975
Accuracy for test set -> 0.5


In [495]:
accuracies = cross_val_score(estimator = model, X = X_train, y = Y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 67.73 %
Standard Deviation: 16.16 %


In [496]:
data_test = pd.read_csv(r'../Datasets/Sri Lankan Dataset - Finalised.csv', header = 0)
data_test.head()

Subject ID  Jitter(local)  Jitter(local, absolute)  Jitter (rap)  \
0          16       0.014680                 0.000086       0.00510   
1          16       0.001029                 0.000047       0.00407   
2          16       0.013350                 0.000056       0.00403   
3          16       0.021640                 0.000113       0.01130   
4          16       0.020900                 0.000095       0.00989   

   Jitter (ppq5)  Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  \
0        0.00615       0.01530          0.08510               0.0814   
1        0.00574       0.01220          0.04188               0.5570   
2        0.00663       0.01210          0.05257               0.7430   
3        0.01200       0.03389          0.06250               0.0781   
4        0.01107       0.02966          0.06128               0.8380   

   Shimmer (apq3)  Shimmer (apq5)  ...  Minimum pitch  Maximum pitch  \
0         0.03719         0.05185  ...         82.429        244.408   
1         0.01337         0.02081  ...        187.378        242.159   
2         0.01663         0.02859  ...        108.624        355.665   
3         0.01745         0.02950  ...        184.991        239.213   
4         0.02133         0.03216  ...        178.835        273.413   

   Number of pulses  Number of periods  Mean period  \
0                94                 93      0.00582   
1               113                112      0.00457   
2               122                120      0.00420   
3                69                 68      0.00524   
4                87                 86      0.00456   

   Standard deviation of period  Fraction of locally unvoiced frames  \
0                      0.001900                              0.00000   
1                      0.000297                              0.00641   
2                      0.000703                              0.02500   
3                      0.000254                              0.07759   
4                      0.000433                              0.01639   

   Number of voice breaks  Degree of voice breaks  status  
0                       0                     0.0       1  
1                       0                     0.0       1  
2                       0                     0.0       1  
3                       0                     0.0       1  
4                       0                     0.0       1  

[5 rows x 28 columns]

In [497]:
data_test.shape

(99, 28)

In [498]:
testing_X = data_test.iloc[:, 1:24].values
testing_X

array([[1.468e-02, 8.550e-05, 5.100e-03, ..., 9.300e+01, 5.820e-03,
        1.900e-03],
       [1.029e-03, 4.700e-05, 4.070e-03, ..., 1.120e+02, 4.570e-03,
        2.970e-04],
       [1.335e-02, 5.610e-05, 4.030e-03, ..., 1.200e+02, 4.200e-03,
        7.030e-04],
       ...,
       [6.290e-03, 6.700e-05, 3.600e-03, ..., 4.430e+02, 1.060e-02,
        1.460e-04],
       [3.880e-03, 4.110e-05, 2.000e-03, ..., 3.310e+02, 1.060e-02,
        1.600e-04],
       [8.550e-03, 7.950e-05, 4.150e-03, ..., 4.580e+02, 9.300e-03,
        2.520e-03]])

In [499]:
testing_X = standard_X.transform(testing_X)
testing_X

array([[ 0.93813831,  0.74520764,  0.19310524, ..., -0.91182336,
        -0.286079  ,  3.88702347],
       [-1.03786733, -0.10987048, -0.05008211, ..., -0.84768418,
        -1.03778556, -0.22050412],
       [ 0.74561853,  0.09223889, -0.05952628, ..., -0.82067821,
        -1.26029071,  0.81983038],
       ...,
       [-0.27632857,  0.33432594, -0.16105109, ...,  0.26968779,
         2.58844688, -0.60742655],
       [-0.6251802 , -0.24090843, -0.53881786, ..., -0.10839578,
         2.58844688, -0.57155295],
       [ 0.0508103 ,  0.61194871, -0.03119377, ...,  0.32032398,
         1.80667206,  5.47571162]])

In [500]:
y_predict_test = model.predict(testing_X)

In [501]:
y_proba = model.predict_proba(testing_X)

In [502]:
y_proba

array([[0.7613904 , 0.23860963],
       [0.08631456, 0.91368544],
       [0.39086682, 0.6091332 ],
       [0.63283074, 0.36716923],
       [0.69000125, 0.30999872],
       [0.15789187, 0.84210813],
       [0.17861533, 0.82138467],
       [0.4722042 , 0.5277958 ],
       [0.20415545, 0.79584455],
       [0.10896623, 0.89103377],
       [0.30854577, 0.69145423],
       [0.2813993 , 0.7186007 ],
       [0.79124105, 0.20875892],
       [0.51305485, 0.48694515],
       [0.61426204, 0.38573796],
       [0.604401  , 0.39559904],
       [0.18079793, 0.81920207],
       [0.24793279, 0.7520672 ],
       [0.8525643 , 0.14743571],
       [0.18277246, 0.81722754],
       [0.19009781, 0.8099022 ],
       [0.1659388 , 0.8340612 ],
       [0.76591516, 0.23408483],
       [0.6222067 , 0.37779328],
       [0.15444613, 0.8455539 ],
       [0.46323955, 0.53676045],
       [0.8584827 , 0.1415173 ],
       [0.83992356, 0.16007642],
       [0.79421854, 0.20578147],
       [0.7706531 , 0.2293469 ],
       [0.

In [503]:
y_predict_test

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0], dtype=int64)

In [504]:
total = 0
for i in y_predict_test:
    total = total + i
    
print(total)

49


In [402]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, random_state=12, test_size = 0.2)

In [403]:
min_max_scaler = preprocessing.MinMaxScaler()
X_train = min_max_scaler.fit_transform(X_train)
X_test = min_max_scaler.transform(X_test)

In [404]:
model = XGBClassifier(max_depth = 3, learning_rate=0.21, n_estimators = 600)
model.fit(X_train, Y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.21, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=600, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [405]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred) # Calulate Confusion matrix for test set.
print(cm)

ValueError: Found input variables with inconsistent numbers of samples: [24, 2]

In [406]:
# Evaluate
print("Accuracy for training set -> ", end = "")
scale_X = min_max_scaler.transform(X)
Y_hat = [round(yhat) for yhat in model.predict(scale_X)]
print(accuracy_score(y, Y_hat)) # Full set accuracy
Y_hat = [round(yhat) for yhat in model.predict(X_test)]
print("Accuracy for test set -> ", end = "")
print(accuracy_score(Y_test, Y_hat)) # Test set accuracy

Accuracy for training set -> 0.9083333333333333
Accuracy for test set -> 0.5416666666666666


In [407]:
accuracies = cross_val_score(estimator = model, X = X_train, y = Y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 62.56 %
Standard Deviation: 7.97 %


In [408]:
data_test = pd.read_csv(r'../Datasets/Sri Lankan Dataset - Finalised.csv', header = 0)
data_test.head()

Subject ID  Jitter(local)  Jitter(local, absolute)  Jitter (rap)  \
0          16       0.014680                 0.000086       0.00510   
1          16       0.001029                 0.000047       0.00407   
2          16       0.013350                 0.000056       0.00403   
3          16       0.021640                 0.000113       0.01130   
4          16       0.020900                 0.000095       0.00989   

   Jitter (ppq5)  Jitter (ddp)  Shimmer (local)  Shimmer (local, db)  \
0        0.00615       0.01530          0.08510               0.0814   
1        0.00574       0.01220          0.04188               0.5570   
2        0.00663       0.01210          0.05257               0.7430   
3        0.01200       0.03389          0.06250               0.0781   
4        0.01107       0.02966          0.06128               0.8380   

   Shimmer (apq3)  Shimmer (apq5)  ...  Minimum pitch  Maximum pitch  \
0         0.03719         0.05185  ...         82.429        244.408   
1         0.01337         0.02081  ...        187.378        242.159   
2         0.01663         0.02859  ...        108.624        355.665   
3         0.01745         0.02950  ...        184.991        239.213   
4         0.02133         0.03216  ...        178.835        273.413   

   Number of pulses  Number of periods  Mean period  \
0                94                 93      0.00582   
1               113                112      0.00457   
2               122                120      0.00420   
3                69                 68      0.00524   
4                87                 86      0.00456   

   Standard deviation of period  Fraction of locally unvoiced frames  \
0                      0.001900                              0.00000   
1                      0.000297                              0.00641   
2                      0.000703                              0.02500   
3                      0.000254                              0.07759   
4                      0.000433                              0.01639   

   Number of voice breaks  Degree of voice breaks  status  
0                       0                     0.0       1  
1                       0                     0.0       1  
2                       0                     0.0       1  
3                       0                     0.0       1  
4                       0                     0.0       1  

[5 rows x 28 columns]

In [409]:
data_test.shape

(99, 28)

In [410]:
testing_X = data_test.iloc[:, 1:24].values
testing_X

array([[1.468e-02, 8.550e-05, 5.100e-03, ..., 9.300e+01, 5.820e-03,
        1.900e-03],
       [1.029e-03, 4.700e-05, 4.070e-03, ..., 1.120e+02, 4.570e-03,
        2.970e-04],
       [1.335e-02, 5.610e-05, 4.030e-03, ..., 1.200e+02, 4.200e-03,
        7.030e-04],
       ...,
       [6.290e-03, 6.700e-05, 3.600e-03, ..., 4.430e+02, 1.060e-02,
        1.460e-04],
       [3.880e-03, 4.110e-05, 2.000e-03, ..., 3.310e+02, 1.060e-02,
        1.600e-04],
       [8.550e-03, 7.950e-05, 4.150e-03, ..., 4.580e+02, 9.300e-03,
        2.520e-03]])

In [411]:
testing_X = min_max_scaler.transform(testing_X)
testing_X

array([[ 0.30951804,  0.25434041,  0.16519174, ...,  0.02581996,
         0.38231429,  0.81985161],
       [-0.0210947 ,  0.13039755,  0.12721239, ...,  0.03907886,
         0.21563227,  0.1074021 ],
       [ 0.27730685,  0.15969314,  0.12573746, ...,  0.04466155,
         0.16629439,  0.28784782],
       ...,
       [ 0.10632114,  0.19478345,  0.10988201, ...,  0.27006281,
         1.01970635,  0.04029051],
       [ 0.0479535 ,  0.11140371,  0.05088496, ...,  0.19190509,
         1.01970635,  0.04651278],
       [ 0.16105595,  0.23502464,  0.13016224, ...,  0.28053036,
         0.84635704,  1.09540912]])

In [412]:
y_predict_test = model.predict(testing_X)

In [413]:
total = 0
for i in y_predict_test:
    total = total + i
    
print(total)

42
